const osmSource = (id, query, note) => ({
  label: "OpenStreetMap / Nominatim", reviewedAt: "2026-10-01", note,
  sourceUrl: `https://www.openstreetmap.org/way/${id}`,
  queryUrl: `https://nominatim.openstreetmap.org/search?${new URLSearchParams({ q: query, countrycodes: "nz", format: "jsonv2", limit: "3" })}`,
  license: "ODbL 1.0",
});

// Point semantics come from OSM, not from the driving service's snapped location.
export const adventureDayTripStops = [
  {
    id: "wanaka-puzzling-world", routeId: "wka-puzzling-world", eventIndexes: [0], drivingStop: true,
    markerType: "activity", iconType: "city", name: "Puzzling World", nameEn: "Puzzling World",
    position: [-44.696992, 169.161698], specificity: "place", kind: "活动地点",
    summary: "上午 Puzzling World，之后返回瓦纳卡午餐。点位来自官网地图链接；驾车线吸附到附近道路，不代表具体停车位。",
    summaryEn: "Morning visit to Puzzling World, then return to Wanaka for lunch. The pin comes from the official map link; the drive follows nearby roads, not a specific parking bay.",
    source: { label: "Puzzling World 官网", reviewedAt: "2026-10-04",
      sourceUrl: "https://www.puzzlingworld.co.nz/about-us/contact-us/",
      note: "官网 Google Maps 目的地坐标，与主站景点点位一致。", repositorySource: "src/components/HotelComparisonDialog.jsx" },
  },
  {
    id: "hawea-albert-town", routeId: "wka-hawea", eventIndexes: [2, 4], drivingStop: true,
    markerType: "town", iconType: "city", name: "Albert Town", nameEn: "Albert Town",
    position: [-44.6832402, 169.1872642], specificity: "town", kind: "城镇参考点",
    summary: "往返 Lake Hāwea 途经的 Albert Town；返程短停可选。点位是城镇参考，不是已核验的河边停车或步道入口。",
    summaryEn: "Albert Town on the Lake Hawea drive, with an optional stop on the return. This is a town reference, not a verified riverside parking area or trail entrance.",
    source: { label: "OpenStreetMap / Nominatim", reviewedAt: "2026-10-04", license: "ODbL 1.0",
      sourceUrl: "https://www.openstreetmap.org/node/176718615",
      note: "OSM place=suburb 的城镇代表点；不作为具体商家或停车入口。" },
  },
  {
    id: "hawea-south-shore", routeId: "wka-hawea", eventIndexes: [3], drivingStop: true,
    markerType: "nature", iconType: "scenic", name: "Lake Hāwea 南岸", nameEn: "Lake Hawea southern shore",
    position: [-44.6108669, 169.2564053], specificity: "area", kind: "湖岸城镇区域",
    summary: "下午 Lake Hāwea 南岸。以官方行程地图中的 Capell Avenue 片区为到达参考，不代表已核验的停车入口；湖岸步行不画成驾车路线。",
    summaryEn: "Afternoon at Lake Hawea's southern shore. The official itinerary map provides a Capell Avenue area reference, not a verified parking entrance. Lakeside walking is not drawn as driving.",
    source: { label: "Lake Wānaka Tourism 官方行程地图", reviewedAt: "2026-10-04",
      sourceUrl: "https://www.wanaka.co.nz/about-wanaka/recommended-trips/wanaka-day-trips/lake-hawea-wanaka-loop/",
      note: "页面 GeoJSON 的 Hawea Store & Kitchen, 33 Capell Avenue 点位；仅作片区参考，不新增商家安排。",
      repositorySource: "src/components/calendar/tripCalendarData.js" },
  },
  {
    id: "wanaka-tree-evening", routeId: "wka-wanaka-tree", eventIndexes: [7], drivingStop: true,
    markerType: "nature", iconType: "scenic", name: "That Wānaka Tree", nameEn: "That Wanaka Tree",
    position: [-44.6985, 169.1175], specificity: "place", kind: "湖岸地标",
    summary: "晚餐后再到湖中树与湖边。保留主站地标点位；驾车只到附近道路，最后步行到湖岸，车辆不能开到树旁。",
    summaryEn: "Return to the tree and lakefront after dinner. The existing landmark pin is retained; driving ends on a nearby road, followed by a walk to the shore.",
    source: { label: "主站既有地标点位 / Lake Wānaka Tourism", reviewedAt: "2026-10-04",
      sourceUrl: "https://www.wanaka.co.nz/explore/waterfall-creek-track/",
      note: "坐标沿用主站湖中树点位；旅游局步道说明用于湖岸步行背景，不证明停车入口。",
      repositorySource: "src/components/HotelComparisonDialog.jsx" },
  },
  {
    id: "glenorchy-bobs-cove", routeId: "zqn-glenorchy", eventIndexes: [1], drivingStop: true,
    markerType: "nature", iconType: "scenic", name: "Bob's Cove", nameEn: "Bob's Cove",
    position: [-45.0699913, 168.5088895], specificity: "place", kind: "步道停车区",
    summary: "点位是 OSM 标记的 Bobs Cove 停车区，作为当天步道停留的公路到达参考；步行路线未绘制。",
    summaryEn: "The OSM Bobs Cove parking area is the road-access reference for this stop. The walking route is not drawn.",
    source: osmSource(1352489780, "Bobs Cove", "OSM amenity=parking 的中心点；不表示具体车位。"),
  },
  {
    id: "glenorchy-bennetts-bluff", routeId: "zqn-glenorchy", eventIndexes: [2], drivingStop: true,
    markerType: "nature", iconType: "scenic", name: "Bennett's Bluff", nameEn: "Bennett's Bluff",
    position: [-45.0288448, 168.4385695], specificity: "area", kind: "断崖与观景区域",
    summary: "点位表示 Bennetts Bluff 断崖区域，不是观景台或停车入口的精确坐标；公路线采用附近道路的吸附点。",
    summaryEn: "This marks the Bennetts Bluff cliff area, not an exact lookout or parking entrance. The road reference uses a nearby snapped road point.",
    source: osmSource(1138001808, "Bennetts Bluff", "OSM natural=cliff 的区域中心；现场停车仍以实际标识为准。"),
  },
  {
    id: "glenorchy-wharf", routeId: "zqn-glenorchy", eventIndexes: [], drivingStop: true,
    markerType: "activity", iconType: "scenic", name: "格林诺奇码头", nameEn: "Glenorchy Wharf",
    position: [-44.8515213, 168.381522], specificity: "place", kind: "码头",
    summary: "复用本事件已指定的 Glenorchy Wharf 目的地；驾车到达附近道路，不表示车辆能够开上码头，也不是午餐餐厅位置。",
    summaryEn: "Glenorchy Wharf is the event's existing destination. Driving ends on a nearby road, not on the pier, and this is not a lunch venue.",
    source: osmSource(1289096084, "Glenorchy Wharf", "OSM man_made=pier 的中心点；目的地语义来自主站事件地图。"),
  },
  {
    id: "glenorchy-lagoon", routeId: "zqn-glenorchy", eventIndexes: [4], drivingStop: false,
    markerType: "nature", iconType: "scenic", name: "Lagoon 木栈道", nameEn: "Glenorchy Lagoon Scenic Walkway",
    position: [-44.8486758, 168.3823911], specificity: "area", kind: "步道区域",
    summary: "点位表示 Glenorchy Lagoon Scenic Walkway 的一段步道，不是唯一入口。步道节点单独标记，不把步行部分画成驾车路线。",
    summaryEn: "This represents one section of the Glenorchy Lagoon Scenic Walkway, not a unique entrance. The walking stop is marked separately from the driving route.",
    source: osmSource(466622220, "Glenorchy Lagoon Walkway", "OSM highway=path 线段的代表点；不声称覆盖整条木栈道。"),
  },
];
