import { northDays, southDays } from "./tripData";

const eventTranslations = {
  "深圳机场值机、托运行李": "Check in and drop checked baggage at Shenzhen Airport",
  "MH0523 深圳 → 吉隆坡": "MH0523 Shenzhen → Kuala Lumpur",
  "抵达吉隆坡 T1，转机 2小时15分": "Arrive at Kuala Lumpur T1; 2 hr 15 min connection",
  "MH0133 吉隆坡 T1 → 奥克兰": "MH0133 Kuala Lumpur T1 → Auckland",
  "抵达奥克兰": "Arrive at Auckland Airport",
  "前往奥克兰市中心酒店": "Travel to the central Auckland hotel",
  "完成入境、取行李": "Clear immigration and collect baggage",
  "留在奥克兰机场过夜候机，不办理酒店入住": "Stay at Auckland Airport overnight for the morning flight; no hotel check-in",
  "前往国内航站楼": "Go to Auckland Airport Domestic Terminal",
  "前往奥克兰机场国内航站楼 D": "Go to Auckland Airport Domestic Terminal D",
  "完成值机与安检，按出票信息前往登机口": "Complete check-in and security, then follow the issued ticket to the gate",
  "JQ295 奥克兰 → 皇后镇（电子客票状态 OK）": "JQ295 Auckland → Queenstown (e-ticket status OK)",
  "抵达皇后镇机场": "Arrive at Queenstown Airport",
  "Budget 皇后镇机场取车（已预订）": "Pick up the booked Budget rental car at Queenstown Airport",
  "取车后在皇后镇活动，15:00 后办理已确认住宿入住": "Spend time in Queenstown after collecting the car, then check in to the confirmed stay from 15:00",
  "抵达、机场午餐": "Arrive at Queenstown Airport and have lunch",
  "Budget 取车（已预订）": "Pick up the booked Budget rental car",
  "入住、湖边散步": "Check in at the booked Queenstown stay, then drive to the lakefront",
  "皇后镇花园、湖边": "Queenstown Gardens and the lakefront",
  "市区午餐": "Lunch in central Queenstown",
  "Skyline 缆车": "Skyline Queenstown gondola",
  "咖啡、逛街": "Coffee and shopping",
  晚餐: "Dinner",
  "皇后镇出发": "Leave Queenstown",
  "Bob’s Cove": "Bob's Cove Track",
  "Bennett’s Bluff": "Bennett's Bluff Lookout",
  "格林诺奇午餐": "Lunch in Glenorchy",
  "Lagoon 木栈道": "Glenorchy Lagoon Boardwalk",
  "回到皇后镇": "Return to Queenstown",
  "慢早餐、湖边散步": "Slow breakfast and a lakefront walk",
  "皇后镇花园或自由逛街": "Queenstown Gardens or free time in town",
  "步行到 Steamer Wharf，按预订场次办理登船": "Walk to Steamer Wharf and check in for the booked sailing",
  "瓦卡蒂普湖往返巡游、Walter Peak 烧烤与农场表演": "Lake Wakatipu cruise, Walter Peak barbecue and farm show",
  "返回皇后镇，自由喝咖啡或回酒店": "Return to Queenstown; have coffee or go back to the hotel",
  "简单晚餐": "Light dinner",
  "退房出发": "Check out and depart",
  "箭镇、午餐": "Arrowtown and lunch",
  "前往瓦纳卡": "Drive towards Wānaka",
  "Crown Range 观景": "Stop at Crown Range Summit",
  "Cardrona 咖啡": "Coffee at Cardrona Hotel",
  "抵达瓦纳卡": "Arrive in Wānaka",
  "湖边、That Wanaka Tree": "Lakefront and That Wānaka Tree",
  午餐: "Lunch",
  "Puzzling World 或 Mount Iron": "Puzzling World or Mount Iron Track",
  "咖啡、看日落": "Coffee and sunset",
  "Lindis Pass 观景": "Stop at Lindis Pass Viewpoint",
  "Omarama 午餐、加油": "Lunch and fuel in Omarama",
  "Lake Pukaki 短停": "Short stop at Lake Pukaki",
  "先到库克山机场办理直升机报到": "Check in for the helicopter flight at Mount Cook Airport",
  "Glacier Highlights 直升机，45分钟含约10—15分钟冰川降落": "Glacier Highlights helicopter flight: 45 minutes including a 10–15 minute glacier landing",
  "在库克山用餐、补充保暖衣物": "Have dinner at Aoraki / Mount Cook and add warm layers",
  "Big Sky 前休息；活动后驾车返回 Twizel": "Rest before Big Sky, then drive back to Twizel after the activity",
  "Big Sky 前休息；活动后返回已预订的 Mt Cook Motel": "Rest before Big Sky, then return to the booked Mt Cook Motel",
  "酒店晚餐、补充保暖衣物": "Dinner at the hotel; add warm layers",
  "Big Sky Stargazing 观星，约75—90分钟": "Big Sky Stargazing, approximately 75–90 minutes",
  "仅在前一日停飞时，候补直升机首班": "First backup helicopter flight only if the previous day was cancelled",
  "最晚离开库克山": "Leave Aoraki / Mount Cook no later than this time",
  "抵达蒂卡波，教堂、湖边、午餐": "Arrive at Lake Tekapo: church, lakefront and lunch",
  "从蒂卡波出发前往奥马鲁": "Leave Lake Tekapo for Ōamaru",
  "抵达奥马鲁、办理入住": "Arrive in Ōamaru and check in",
  "奥马鲁港边步道找新西兰海狗；保持至少20米，不喂、不摸、不挡住海狗与海之间的路线": "Look for New Zealand fur seals along Ōamaru Harbour; keep at least 20 m away, never feed or touch them, and do not stand between a seal and the sea",
  "提前吃晚餐，准备企鹅晚场": "Have an early dinner before the evening penguin viewing",
  "提前30分钟抵达 Ōamaru Blue Penguin Colony；晚场禁止拍照、录像及亮屏": "Arrive at Ōamaru Blue Penguin Colony 30 minutes early; cameras, filming and bright screens are prohibited during evening viewing",
  "小蓝企鹅归巢：General 成人 NZD 50、Premium 成人 NZD 70（2026-07-29核验；预订时重新确认余量）": "Little penguin evening viewing: General NZD 50 or Premium NZD 70 per adult (verified 29 Jul 2026; recheck availability before booking)",
  "返回奥马鲁住宿休息": "Return to the Ōamaru accommodation",
  "奥马鲁退房，驾车前往基督城": "Check out in Ōamaru and drive to Christchurch",
  "Timaru 海边或咖啡短休": "Take a short waterfront or coffee break in Timaru",
  "Ashburton 午餐并让驾驶员休息": "Stop for lunch and a driver break in Ashburton",
  "抵达基督城市中心，停车并办理入住": "Arrive in central Christchurch, park and check in",
  "Riverside Market、雅芳河畔": "Riverside Market and the Avon River precinct",
  "基督城植物园与 Hagley Park": "Christchurch Botanic Gardens and Hagley Park",
  "基督城市中心午餐": "Lunch in central Christchurch",
  "从市中心前往基督城机场": "Travel from central Christchurch to the airport",
  "乘公交或出租车返回基督城市中心": "Return to central Christchurch by bus or taxi",
  "Cathedral Square、New Regent Street": "Cathedral Square and New Regent Street",
  "基督城市区晚餐": "Dinner in central Christchurch",
  "酒店退房，早餐后取车出发": "Check out after breakfast and depart by car",
  "从基督城市中心前往机场，途中加满油并预留道路缓冲": "Drive from central Christchurch to the airport, refuel en route and allow for traffic",
  "Budget 基督城机场还车（已预订）": "Return the booked Budget car at Christchurch Airport",
  "步行进入国内航站楼，办理值机与安检": "Walk into the domestic terminal for check-in and security",
  "JQ236 基督城 → 奥克兰（电子客票状态 OK）": "JQ236 Christchurch → Auckland (e-ticket status OK)",
  "抵达奥克兰，随后前往奥克兰市中心酒店": "Arrive in Auckland, then travel to the central Auckland hotel",
  "抵达奥克兰": "Arrive at Auckland Airport",
  "从市中心酒店出发": "Leave the central Auckland hotel",
  "Queen Street、Britomart": "Queen Street and Britomart",
  "Commercial Bay 午餐": "Lunch at Commercial Bay",
  "Westfield Newmarket": "Westfield Newmarket",
  "返回市中心酒店": "Return to the central Auckland hotel",
  "SkyCity Coach Terminal 报到": "Check in at SkyCity Coach Terminal, 102 Hobson Street",
  "大巴前往霍比屯": "Take the GreatSights coach to Hobbiton",
  "抵达 SkyCity Coach Terminal": "Arrive back at SkyCity Coach Terminal",
  "送回指定奥克兰市中心酒店": "Hotel drop-off begins for designated central Auckland hotels",
  "大巴返回奥克兰": "Take the GreatSights coach back to Auckland",
  "退房后寄存行李": "Check out and leave luggage",
  "奥克兰轻松半日": "Relaxed half-day in central Auckland",
  "午餐、返回酒店取行李": "Have lunch, then collect luggage from the hotel",
  "前往奥克兰机场": "Travel to Auckland Airport",
  "抵达国际航站楼、寄存或整理行李": "Arrive at the international terminal and store or reorganise luggage",
  出发: "Depart",
  "抵达 The Shire’s Rest": "Arrive at The Shire's Rest",
  "霍比屯游览": "Hobbiton Movie Set tour",
  "办理国际值机": "Check in for the international flight",
  "前往登机口": "Proceed to the departure gate",
  "MH0132 奥克兰 → 吉隆坡，07:55 抵达 T1": "MH0132 Auckland → Kuala Lumpur; arrive at T1 at 07:55",
  "MH0522 吉隆坡 T1 → 深圳，次日 01:15 抵达": "MH0522 Kuala Lumpur T1 → Shenzhen; arrive at 01:15 the next day",
};

const dayTranslations = {
  "9月28日": ["Shenzhen → Kuala Lumpur → Auckland", "Connect in Malaysia, then wait overnight at Auckland Airport", "No hotel tonight; remain at the airport for the morning JQ295 flight."],
  "9月29日": ["Auckland → Queenstown", "JQ295 morning flight and 11:00 South Island car pickup", "Confirmed stay; unlock private details to view the property and arrival information."],
  "9月30日": ["Queenstown", "Gardens, lakefront and Skyline", "Confirmed stay; unlock private details to view the property and arrival information."],
  "10月1日": ["Queenstown ⇄ Glenorchy", "Relaxed half-day lakefront drive", "Confirmed stay; unlock private details to view the property and arrival information."],
  "10月2日": ["Walter Peak Lake Cruise", "High-country barbecue and farm show", "Confirmed stay; unlock private details to view the property and arrival information."],
  "10月3日": ["Queenstown → Arrowtown → Wānaka", "Crown Range and Cardrona", "Confirmed stay; unlock private details to view the property and arrival information."],
  "10月4日": ["Wānaka", "A full day without changing hotels", "Confirmed stay; unlock private details to view the property and arrival information."],
  "10月5日": ["Wānaka → Aoraki / Mount Cook", "Glacier helicopter landing and Big Sky Stargazing", "Confirmed stay; unlock private details to view the property and arrival information."],
  "10月6日": ["Aoraki / Mount Cook → Lake Tekapo → Ōamaru", "Short Lake Tekapo stop and 20:00 little-penguin viewing", "Confirmed stay; unlock private details to view the property and arrival information."],
  "10月7日": ["Ōamaru → Christchurch", "Drive north and enjoy a slow late afternoon in central Christchurch", "Confirmed stay; unlock private details to view the property and arrival information."],
  "10月8日": ["Christchurch → Auckland", "Return the car at 11:00, then take JQ236 at 13:50", "Confirmed stay; unlock private details to view the property and arrival information."],
  "10月9日": ["Auckland ⇄ Hobbiton", "GreatSights GS10H coach day tour", "Confirmed stay; unlock private details to view the property and arrival information."],
  "10月10日": ["Auckland half-day → Auckland Airport", "Leave luggage, enjoy an easy half-day and transfer to the airport", "Checkout is confirmed; unlock private details to view the stay information."],
  "10月11日": ["Auckland → Shenzhen", "International return flights via Kuala Lumpur", "Overnight · On board."],
};

const weekdayTranslations = {
  周一: "Monday",
  周二: "Tuesday",
  周三: "Wednesday",
  周四: "Thursday",
  周五: "Friday",
  周六: "Saturday",
  周日: "Sunday",
};

function dateInEnglish(date) {
  const match = date.match(/(\d+)月(\d+)日/);
  return match ? `${match[1]}/${match[2]}` : date;
}

function translateDay(day) {
  const [title, subtitle, stay] = dayTranslations[day.date] ?? [day.title, day.subtitle, day.stay];
  return {
    ...day,
    alternative: day.alternative && day.date === "10月6日" ? {
      title: "Optional add-on · Kātiki Point",
      desc: "Consider it only if weather, energy and time all allow. It is not part of the main route and must not jeopardise arrival at the little-penguin colony by 19:30.",
    } : day.alternative,
    dateKey: day.date,
    displayDate: dateInEnglish(day.date),
    events: day.events.map(([time, text]) => [time, eventTranslations[text] ?? text]),
    stay,
    subtitle,
    title,
    weekday: weekdayTranslations[day.weekday] ?? day.weekday,
  };
}

export const southDaysEn = southDays.map(translateDay);
export const northDaysEn = northDays.map(translateDay);
export const itineraryDaysEn = [...southDaysEn, ...northDaysEn];
