const xhs = (post) => ({
  mediaType: "image",
  ...post,
  platform: "小红书",
  source: "小红书 · 已核验原帖",
  sourceEn: "Xiaohongshu · verified post",
  verified: true,
  isSearchEntry: false,
  sentiment: post.stance,
});

// These groups stay empty until five authenticated, individually opened
// Xiaohongshu posts have been supplied for the topic, including both positive
// and pitfall coverage. Search-result snippets are intentionally not accepted.
export const verifiedHobbitonGuides = [];
export const verifiedRotoruaGuides = [];
export const verifiedReturnAirportGuides = [];

export const verifiedAucklandShoppingGuides = [
  xhs({
    title: "奥克兰Newmarket逛街+集市+景点+停车全攻略",
    titleEn: "A complete Newmarket guide to shopping, markets, sights and parking",
    author: "新西兰玩点啥",
    coverImage: "/new-zealand-slow-trip-2026/images/xhs-auckland-newmarket-guide.webp",
    coverAlt: "Newmarket 逛街攻略原帖首图",
    excerpt: "作者把 Newmarket 的 Westfield、Teed Street、Osborne Lane、Broadway 与周边集市和景点串成一套逛街动线，并整理公交、火车和停车选择。",
    excerptEn: "The author links Westfield Newmarket, Teed Street, Osborne Lane, Broadway and nearby markets and sights into one shopping route, with public-transport and parking options.",
    points: [
      "Newmarket 集中约 600 家店，可按 Westfield、Teed Street、Osborne Lane 和 Broadway 分区步行。",
      "帖子提到 Westfield Plus 登记车牌可享三小时免费停车，周边另有 13 个停车场。",
      "公交和火车都可抵达，适合不想在市区反复找车位时使用。",
    ],
    pointsEn: [
      "Newmarket has roughly 600 shops that can be explored on foot by grouping Westfield, Teed Street, Osborne Lane and Broadway.",
      "The post says a registered vehicle in Westfield Plus receives three hours of free parking and lists 13 nearby car parks.",
      "Both buses and trains reach the area, useful when you want to avoid repeatedly searching for city parking.",
    ],
    tip: "帖子包含 Untouched World 推广；折扣、免费停车时长和登记条件须在 Westfield 官方页面或现场再次确认。",
    tipEn: "The post promotes Untouched World. Reconfirm discounts, free-parking duration and registration requirements with Westfield or on site.",
    stance: "positive",
    url: "https://www.xiaohongshu.com/explore/6892a4b50000000022021a7a",
  }),
  xhs({
    title: "奥克兰CBD购物攻略｜步行一天打卡版🔥",
    titleEn: "Auckland CBD shopping guide: a full day on foot",
    author: "明天一定要早起",
    coverImage: "/new-zealand-slow-trip-2026/images/xhs-auckland-cbd-shopping.webp",
    coverAlt: "奥克兰 CBD 购物攻略原帖首图",
    excerpt: "作者按 Commercial Bay、Queen Street、Britomart、High Street 和 Vulcan Lane 规划一日步行购物，并补充超市与药房采购点。",
    excerptEn: "The author plans a full shopping day on foot through Commercial Bay, Queen Street, Britomart, High Street and Vulcan Lane, with supermarket and pharmacy stops included.",
    points: [
      "Commercial Bay、Queen Street、Britomart、High Street 与 Vulcan Lane 可连续步行串联。",
      "日用品可在 Countdown、The Warehouse 和 Chemist Warehouse 集中采购。",
      "帖子提醒多数商店约 18:00 关门，周四常有延长营业。",
    ],
    pointsEn: [
      "Commercial Bay, Queen Street, Britomart, High Street and Vulcan Lane connect into a practical walking route.",
      "Countdown, The Warehouse and Chemist Warehouse cover many everyday shopping needs.",
      "The post notes that many stores close around 6 pm, with later trading often available on Thursdays.",
    ],
    tip: "把关门时间当作动线约束，但营业安排会变化；出发当天逐店核对，贵重采购尽量放在前半天。",
    tipEn: "Use closing times as a route constraint, but verify each store on the day and place high-priority purchases earlier.",
    stance: "positive",
    url: "https://www.xiaohongshu.com/explore/6a609cd3000000000402bf2e",
  }),
  xhs({
    title: "在新西兰以为是“免费停车”，结果出不来",
    titleEn: "Thought the parking was free—then could not exit",
    author: "珍妮心儿",
    coverImage: "/new-zealand-slow-trip-2026/images/xhs-auckland-westfield-exit.webp",
    coverAlt: "Westfield Newmarket 停车避坑原帖首图",
    excerpt: "作者在 Westfield Newmarket 因未完成会员注册和车牌绑定，又遇到银行卡无法支付而被卡在出口，提醒“免费停车”通常附带账户与车辆登记条件。",
    excerptEn: "At Westfield Newmarket, the author had not completed membership and licence-plate registration, then had a card-payment failure at the exit—showing that 'free parking' often has account and vehicle conditions.",
    points: [
      "停车场使用车牌自动识别，需下载或注册 Westfield 账户并正确绑定车牌。",
      "评论称平日通常免费三小时、周末两小时，但实际规则须以入场当天为准。",
      "首次误操作可尝试邮件申诉，但不能假定一定免除费用。",
    ],
    pointsEn: [
      "The car park uses automatic licence-plate recognition, so the Westfield account and vehicle registration must be completed correctly.",
      "Comments mention three free hours on weekdays and two on weekends, but the rule must be checked on the day.",
      "A first-time mistake may be appealed by email, but a waiver is not guaranteed.",
    ],
    tip: "入场前完成 App、会员和车牌绑定，并准备第二种支付方式。",
    tipEn: "Set up the app, membership and licence plate before entry and carry a backup payment method.",
    stance: "pitfall",
    url: "https://www.xiaohongshu.com/explore/6965c6e2000000000a02a003",
  }),
  xhs({
    title: "Newmarket的停车黑点",
    titleEn: "A Newmarket parking trap",
    author: "Amy在澳新",
    coverImage: "/new-zealand-slow-trip-2026/images/xhs-auckland-newmarket-tow-zone.webp",
    coverAlt: "Newmarket 停车禁停时段原帖首图",
    excerpt: "作者提醒 Kingdon Street 永发和味千对面存在工作日高峰禁停与其他时段短时装卸限制，误读标牌可能被拖车。",
    excerptEn: "The author warns that the Kingdon Street area opposite Yong Fa and Ajisen has weekday peak no-stopping restrictions and short loading limits at other times; misreading the sign can result in towing.",
    points: [
      "评论对牌面解读为工作日 07:00–09:00、16:00–18:00 禁停。",
      "其他时段也并非普通长停区域，而是约五分钟装卸限制。",
      "AT Park 未必主动提示这类路边时段规则，必须现场看完整标牌。",
    ],
    pointsEn: [
      "Commenters interpret the sign as no stopping on weekdays from 7–9 am and 4–6 pm.",
      "Outside those periods it is still not ordinary long-stay parking, but a roughly five-minute loading zone.",
      "AT Park may not surface every curbside time restriction, so read the complete physical sign.",
    ],
    tip: "不要只看停车 App 或跟随前车；逐行读标牌的日期、时段和装卸限制，拿不准就换正式停车场。",
    tipEn: "Do not rely only on the parking app or other parked cars. Read every date, time and loading restriction; use a proper car park when unsure.",
    stance: "pitfall",
    url: "https://www.xiaohongshu.com/explore/66c5786b000000001f01d7b4",
  }),
  xhs({
    title: "奥克兰购物🛍️🛍️🛍️买买买",
    titleEn: "Auckland shopping spree: CBD, Sylvia Park and Newmarket",
    author: "Wendy的山野日常",
    coverImage: "/new-zealand-slow-trip-2026/images/xhs-auckland-shopping-spree.webp",
    coverAlt: "奥克兰购物行程原帖首图",
    excerpt: "作者分享 CBD 奢侈品店、Sylvia Park、Newmarket 和 Chemist Warehouse 的组合采购，并记录机场免税提货需要的护照与返程航班信息。",
    excerptEn: "The author combines CBD luxury stores, Sylvia Park, Newmarket and Chemist Warehouse, and records that airport duty-free pickup requires passport and outbound-flight details.",
    points: [
      "CBD 奢侈品店可 walk-in 试购，机场免税提货需填写护照和返程航班。",
      "作者建议提前一至两天购买，为配送到机场留出时间。",
      "Sylvia Park 有免费 Wi-Fi、帖子称停车四小时，并集中综合品牌和华人超市。",
    ],
    pointsEn: [
      "CBD luxury stores may accept walk-ins; airport duty-free pickup requires passport and outbound-flight details.",
      "The author recommends buying one or two days early to allow delivery to the airport pickup point.",
      "Sylvia Park offers free Wi-Fi and, according to the post, four-hour parking, with mainstream brands and an Asian supermarket.",
    ],
    tip: "库存、折扣、停车和免税提货规则都需向门店确认。",
    tipEn: "Confirm stock, discounts, parking and duty-free pickup directly with stores.",
    stance: "positive",
    url: "https://www.xiaohongshu.com/explore/68908fd2000000002502a587",
  }),
];

export const verifiedFlightTransitGuides = [
  xhs({
    title: "马航吉隆坡国际转国际攻略",
    titleEn: "Malaysia Airlines international transfer guide for Kuala Lumpur",
    author: "燕子不会飞",
    coverImage: "/new-zealand-slow-trip-2026/images/xhs-klia-malaysia-airlines-transfer.webp",
    coverAlt: "马航吉隆坡国际转国际攻略小红书封面",
    excerpt: "作者分享马航联程在首段领取两张登机牌、行李直挂的转机流程，并说明吉隆坡 T1 主楼和卫星楼之间的移动方式。",
    excerptEn: "The author explains a Malaysia Airlines through-ticket transfer with both boarding passes issued at origin and baggage checked through, including how to move between KLIA Terminal 1's main and satellite buildings.",
    points: [
      "联程且行李直挂时，无需在吉隆坡入境或提取行李。",
      "T1 主楼使用 G/H 登机区，卫星楼使用 C 区，跨楼需搭无人列车。",
      "登机口可能临时变更，抵达后仍要查看航显二次确认。",
    ],
    pointsEn: [
      "On a through ticket with checked-through baggage, no Malaysian immigration or baggage claim is needed.",
      "The T1 main building uses G/H gates and the satellite building uses C gates; the automated train connects them.",
      "Gates may change at short notice, so recheck the departure boards after arrival.",
    ],
    tip: "作者给出的步行时间和误机改签经历只能作参考；衔接保障必须以马航当日确认为准。",
    tipEn: "Treat the author's walking-time estimates and missed-connection rebooking experience as a reference only; confirm connection protection with Malaysia Airlines on the day.",
    stance: "positive",
    url: "https://www.xiaohongshu.com/explore/6a51ca0e0000000011005c00",
  }),
  xhs({
    title: "奥克兰机场入境全记录（含血泪教训😭）",
    titleEn: "Auckland Airport arrival walkthrough and hard-learned lessons",
    author: "摩羯知夏",
    coverImage: "/new-zealand-slow-trip-2026/images/xhs-auckland-arrival-pitfalls.webp",
    coverAlt: "奥克兰机场入境全记录小红书封面",
    excerpt: "作者记录了奥克兰机场人工入境排队、电子申报和接机分区，并以现场见闻提醒食品、药品和户外用品必须如实申报。",
    excerptEn: "The author documents manual immigration queues, the digital arrival declaration and pickup zones at Auckland Airport, while warning from an observed incident that food, medicines and outdoor gear should be declared honestly.",
    points: [
      "提前或落地后完成电子申报，并保存申报结果截图。",
      "作者在 All Passports 人工通道等待约 40 分钟，并提到符合条件的中国护照可尝试 eGate。",
      "接机时确认 Ride Share / Pick Up 标识和具体 zone，避免在航站楼外来回寻找。",
    ],
    pointsEn: [
      "Complete the digital declaration before travel or after landing and save a screenshot of the result.",
      "The author waited about 40 minutes in the All Passports queue and notes that eligible Chinese passports may use eGate.",
      "For pickup, confirm the Ride Share / Pick Up sign and exact zone rather than wandering outside the terminal.",
    ],
    tip: "不确定是否需要申报的食品、药品或户外用品也应主动申报；帖子中的罚款见闻不能代替新西兰海关规则。",
    tipEn: "Declare food, medicines or outdoor equipment whenever unsure; the post's observed fine does not replace New Zealand Customs and Biosecurity rules.",
    stance: "pitfall",
    url: "https://www.xiaohongshu.com/explore/6970d875000000000e00c8be",
  }),
  xhs({
    title: "✈️吉隆坡转机血泪史！这些深坑我替你们踩了",
    titleEn: "Kuala Lumpur transfer ordeal: pitfalls learned the hard way",
    author: "萌小猪",
    coverImage: "/new-zealand-slow-trip-2026/images/xhs-klia-transfer-pitfalls.webp",
    coverAlt: "吉隆坡转机血泪史小红书封面",
    excerpt: "作者在三小时内转机并需要重新托运，最终错过第二段且遗失护照；复盘集中在跨航站楼、付款联网、餐厅等待和多次安检的时间风险。",
    excerptEn: "The author had under three hours to connect with baggage re-check, missed the onward flight and lost a passport; the review focuses on cross-terminal transfers, online payment, restaurant delays and repeated security checks.",
    points: [
      "T2 到 T1 免费巴士等待时间不稳定，机场快线付款还需要可用网络。",
      "作者遇到餐厅出餐约 25 分钟，短转机不适合离开机场打卡或专程购物。",
      "转机步行距离长，托运与安检可能提前截止，不能只按计划起飞时间倒推。",
    ],
    pointsEn: [
      "The free T2-to-T1 bus can be unpredictable, while paying for the airport train requires a working internet connection.",
      "The author waited about 25 minutes for food; a short connection is not the time to leave the airport or make a special shopping stop.",
      "Transfer walks are long and baggage/security cutoffs can be earlier than departure time, so do not plan backwards from takeoff alone.",
    ],
    tip: "护照和登机牌全程放在固定贴身位置；若涉及换航站楼或重新托运，三小时也可能不足。",
    tipEn: "Keep passport and boarding passes in one secure, on-body location throughout; even three hours may be insufficient when changing terminals or rechecking baggage.",
    stance: "pitfall",
    url: "https://www.xiaohongshu.com/explore/68e430d10000000004013791",
  }),
  xhs({
    title: "丝滑转机！！吉隆坡转机全攻略",
    titleEn: "A smooth Kuala Lumpur transfer: complete practical guide",
    author: "王宅宅",
    coverImage: "/new-zealand-slow-trip-2026/images/xhs-klia-smooth-transfer.webp",
    coverAlt: "丝滑吉隆坡转机攻略小红书封面",
    excerpt: "作者按同航站楼直挂、不直挂入境再值机以及 T2 转 T1 三种场景拆解所需时间，强调行李和航站楼组合决定转机难度。",
    excerptEn: "The author breaks transfer time into three scenarios—same-terminal through baggage, immigration and re-check without through baggage, and T2-to-T1—showing how baggage handling and terminal pairing determine difficulty.",
    points: [
      "同航站楼且行李直挂，作者最快约半小时完成转机。",
      "行李不直挂需要填 MDAC、入境、提取行李再值机，作者估算约 2–3 小时。",
      "T2 到 T1 的巴士车程约 25 分钟但时刻不稳定；还要计算入境、值机和登机前二次安检。",
    ],
    pointsEn: [
      "For the same terminal with checked-through baggage, the author's fastest transfer took about 30 minutes.",
      "Without checked-through baggage, MDAC, immigration, baggage claim and re-check may take roughly two to three hours in the author's estimate.",
      "The T2-to-T1 bus takes about 25 minutes but can be irregular; also budget for immigration, check-in and secondary gate security.",
    ],
    tip: "先向航司确认航站楼和行李是否直挂，再决定转机缓冲；个人耗时不代表你当日排队情况。",
    tipEn: "Confirm terminals and through-baggage status with the airline before setting the buffer; one traveller's timing does not predict queues on your date.",
    stance: "positive",
    url: "https://www.xiaohongshu.com/explore/66386175000000001e021a9f",
  }),
  xhs({
    title: "马航联程 吉隆坡t1中转攻略（赶不上版）",
    titleEn: "Malaysia Airlines connection at KLIA T1: the missed-flight version",
    author: "小李赴日",
    coverImage: "/new-zealand-slow-trip-2026/images/xhs-klia-missed-connection.webp",
    coverAlt: "马航吉隆坡 T1 联程误机攻略小红书封面",
    excerpt: "作者搭乘上海经吉隆坡至槟城的马航联程，只有一小时衔接且首段延误 15 分钟；从 C5 到 B5 经摆渡车、入境和安检后未赶上第二段。",
    excerptEn: "The author travelled Shanghai–Kuala Lumpur–Penang on a Malaysia Airlines through ticket with a one-hour connection; a 15-minute inbound delay plus the C5-to-B5 bus, immigration and security led to a missed onward flight.",
    points: [
      "从 C5 到 B5 需按 A/B/G/H 指示上下楼，并搭乘约 5 分钟的摆渡车。",
      "作者背 40L 包跑约 800 米，到达时登机口已经关闭；一小时中转容错极低。",
      "工作人员引导至 transfer counter，在有余位时免费改到下一班；作者主动询问 compensation 后获得餐券。",
    ],
    pointsEn: [
      "C5 to B5 requires following the A/B/G/H signs between levels and taking a roughly five-minute transfer bus.",
      "The author ran about 800 metres with a 40-litre pack but found the gate closed; a one-hour connection leaves almost no margin.",
      "Staff directed the author to the transfer counter and moved the booking to the next available flight; a meal voucher was provided only after compensation was requested.",
    ],
    tip: "一小时衔接是在赌延误和排队；记住转机柜台英文为 transfer counter，误机后立即找柜台并主动询问改签与餐券。",
    tipEn: "A one-hour connection is a gamble against delays and queues. Ask for the transfer counter immediately after a misconnection and proactively enquire about rebooking and meal vouchers.",
    stance: "pitfall",
    url: "https://www.xiaohongshu.com/explore/679837bb000000002901f25c",
  }),
];
