const verifiedXhsPost = (post) => ({
  mediaType: "image",
  ...post,
  platform: "小红书",
  source: "小红书 · 已核验原帖",
  sourceEn: "Xiaohongshu · verified post",
  verified: true,
  isSearchEntry: false,
  sentiment: post.stance,
});

export const verifiedQueenstownRegionGuides = [
  verifiedXhsPost({
    title: "狠狠避雷皇后镇旋转停车场",
    titleEn: "Avoid this Queenstown spiral car park",
    author: "幻樱",
    coverImage: "/new-zealand-slow-trip-2026/images/xhs-queenstown-spiral-car-park.webp",
    coverAlt: "皇后镇旋转停车场原帖首图",
    excerpt: "作者称在皇后镇一处旋转停车场停约 3 小时支付 24 新西兰元，且入场时没有看到清晰价格。评论提到 Skyline 门票可能在付款前刷票获得优惠、部分街边车位傍晚可能免费，以及 Lakeview 相对便宜，但这些说法都需要到场复核。",
    excerptEn: "The author says roughly three hours in a Queenstown spiral car park cost NZD 24 and that pricing was not clearly visible on entry. Comments mention a possible Skyline-ticket discount before payment, some street spaces becoming free in the evening, and Lakeview being cheaper, but every claim requires on-site verification.",
    points: [
      "入场前先找完整费率、封顶价和付款规则。",
      "没有看清价格时，不要默认市中心停车场收费合理。",
      "评论里的优惠、免费时段和 Lakeview 价格都不是现场保证。",
    ],
    pointsEn: [
      "Find the full tariff, daily cap and payment rules before entering.",
      "If pricing is unclear, do not assume a central car park will be reasonably priced.",
      "Discounts, free periods and Lakeview prices mentioned in comments are not on-site guarantees.",
    ],
    tip: "到场以入口牌、停车机和官方规则为准，必要时先拍照再决定是否驶入。",
    tipEn: "Follow entrance signs, payment machines and official rules on arrival; photograph unclear terms before deciding whether to enter.",
    stance: "pitfall",
    url: "https://www.xiaohongshu.com/explore/69770795000000000c035e67",
  }),
  verifiedXhsPost({
    title: "皇后镇自驾｜箭镇一般，改道格林诺奇给到夯",
    titleEn: "Queenstown self-drive: Arrowtown underwhelmed, Glenorchy delivered",
    author: "奥晞Aki",
    coverImage: "/new-zealand-slow-trip-2026/images/xhs-queenstown-arrowtown-glenorchy-drive.webp",
    coverAlt: "皇后镇、箭镇与格林诺奇自驾原帖首图",
    excerpt: "作者认为箭镇的人文氛围不错，但景观没有达到预期；相比之下，皇后镇至格林诺奇湖岸公路的半日行程更值得，并推荐 Paradise Wharf。由于事先没有攻略而开得较快，作者错过了沿途观景点。",
    excerptEn: "The author liked Arrowtown's heritage atmosphere but found its scenery below expectations. A half-day on the Queenstown–Glenorchy lakeside road felt more worthwhile, with Paradise Wharf recommended. Driving too quickly without prior planning caused the author to miss viewpoints.",
    points: [
      "箭镇与格林诺奇侧重点不同：前者偏人文，后者偏湖岸景观。",
      "Paradise Wharf 可作为格林诺奇方向的重点停靠。",
      "提前标记观景点，避免开过后临时刹车或倒车寻找入口。",
    ],
    pointsEn: [
      "Arrowtown and Glenorchy serve different interests: heritage versus lakeside scenery.",
      "Paradise Wharf can be treated as a priority stop toward Glenorchy.",
      "Mark viewpoints beforehand so a missed turn never triggers sudden braking or reversing.",
    ],
    tip: "只在正式观景位和停车区停靠；错过入口就继续前行，不在道路上急停。",
    tipEn: "Stop only at designated viewpoints and parking areas. If an entrance is missed, continue rather than stopping suddenly.",
    stance: "positive",
    url: "https://www.xiaohongshu.com/explore/69db5093000000001a035b9a",
  }),
  verifiedXhsPost({
    title: "🇳🇿新西兰南岛自驾｜皇后镇-格林诺奇-箭镇",
    titleEn: "South Island self-drive: Queenstown, Glenorchy and Arrowtown",
    author: "俣(yǔ)辰",
    coverImage: "/new-zealand-slow-trip-2026/images/xhs-queenstown-glenorchy-arrowtown-route.webp",
    coverAlt: "皇后镇、格林诺奇与箭镇路线原帖首图",
    excerpt: "帖子串联 Seven Mile、Wilson、Bob's Cave、Bennetts、Twenty Five Mile 与 Glenorchy，并提醒皇后镇免费车位难找，可先问房东；箭镇 wine store 左侧有大型免费停车场。作者认为 Crown Range 发卡弯多且急，慢车也会承受后车压力。",
    excerptEn: "The post links Seven Mile, Wilson, Bob's Cave, Bennetts, Twenty Five Mile and Glenorchy. It warns that free Queenstown parking is difficult to find and suggests asking the host, while noting a large free car park left of the Arrowtown wine store. The author describes Crown Range as having many tight hairpins and pressure from following traffic.",
    points: [
      "格林诺奇方向的多个湖岸停靠点适合提前按顺序收藏。",
      "皇后镇停车先向住宿方确认，箭镇停车规则仍需现场看牌。",
      "不熟悉山路或天气恶劣时，可考虑经水果小镇的较平缓路线。",
    ],
    pointsEn: [
      "Save the Glenorchy lakeside stops in route order before departure.",
      "Ask the accommodation about Queenstown parking and still read current Arrowtown signs.",
      "When unfamiliar with mountain driving or in poor weather, consider the gentler route via Cromwell.",
    ],
    tip: "限速 100 不是建议车速，必须按弯道、天气和能见度降速；有安全让车位再让后车通过。",
    tipEn: "A 100 km/h limit is not a target speed. Slow for bends, weather and visibility, and let traffic pass only at a safe pull-off.",
    stance: "pitfall",
    url: "https://www.xiaohongshu.com/explore/69e1b26e000000002003a8e6",
  }),
  verifiedXhsPost({
    title: "🇳🇿南岛D6｜格林诺奇值得发呆半日🏡",
    titleEn: "South Island day 6: Glenorchy is worth a relaxed half-day",
    author: "是小鹿吖🦌",
    coverImage: "/new-zealand-slow-trip-2026/images/xhs-glenorchy-relaxed-half-day.webp",
    coverAlt: "格林诺奇半日游原帖首图",
    excerpt: "作者依次走过 Seven Mile、Wilson、Bennett's、Twenty Five Mile、Glenorchy 与 Rees Bridge；Bennett's 从停车点约需 10 分钟缓坡步行。作者在评论中认为上午出发、安排大半天足够。",
    excerptEn: "The author's route covers Seven Mile, Wilson, Bennett's, Twenty Five Mile, Glenorchy and Rees Bridge. Bennett's involves about a ten-minute gentle uphill walk from parking. In comments, the author says a morning departure and most of a day felt sufficient.",
    points: [
      "多个停靠点可以组成节奏宽松的湖岸半日。",
      "Bennett's 需要预留约 10 分钟缓坡步行和拍照时间。",
      "上午出发、大半天完成是作者个人节奏，应为天气和人流留缓冲。",
    ],
    pointsEn: [
      "Several stops can form a relaxed lakeside half-day.",
      "Allow roughly ten minutes of gentle uphill walking plus photo time at Bennett's.",
      "A morning start and most of a day reflect the author's pace; retain a buffer for weather and crowds.",
    ],
    tip: "正文提到可路边停车，但实际只能使用正规停车位或明确允许停车的区域，不能占用车道或路肩。",
    tipEn: "Although the post mentions roadside parking, use only designated spaces or areas where parking is explicitly permitted; never occupy the carriageway or an unsafe shoulder.",
    stance: "positive",
    url: "https://www.xiaohongshu.com/explore/6a1049470000000036001fb1",
  }),
  verifiedXhsPost({
    title: "新西兰天堂之路🚗格林诺奇一天自驾游攻略",
    titleEn: "New Zealand's road to paradise: a Glenorchy self-drive day",
    author: "艾伦爱旅游",
    coverImage: "/new-zealand-slow-trip-2026/images/xhs-glenorchy-paradise-road-trip.webp",
    coverAlt: "格林诺奇天堂之路原帖首图",
    excerpt: "路线包含 Seven Mile、Wilson、Bennett's、红房子和泻湖，且沿途餐饮选择较少。虽然主体体验正面，但作者因在 Glenorchy 镇内超速被罚，评论确认了罚单；小镇限速为 30。Paradise 方向碎石路也可能不在租车保障范围内。",
    excerptEn: "The route includes Seven Mile, Wilson, Bennett's, the red shed and the lagoon, with few food options along the way. Despite an otherwise positive trip, the author received a speeding fine in Glenorchy, confirmed in comments; the town limit is 30. Gravel roads toward Paradise may also fall outside rental cover.",
    points: [
      "进入 Glenorchy 镇区立即留意 30 限速和执法。",
      "沿途餐饮少，出发前准备饮水和简餐。",
      "驶入 Paradise 碎石路前必须核对租车合同的未铺装路保障。",
    ],
    pointsEn: [
      "Watch for the 30 km/h limit and enforcement immediately on entering Glenorchy.",
      "Food options are limited, so carry water and a simple meal.",
      "Check the rental contract's unsealed-road cover before driving toward Paradise.",
    ],
    tip: "不要用作者“不知道是否保障”作为依据；租车合同未明确允许就不要进入碎石路，镇内也要严格按 30 行驶。",
    tipEn: "Do not rely on the author's uncertainty about cover. Avoid gravel roads unless the rental contract explicitly permits them, and obey the 30 km/h town limit.",
    stance: "pitfall",
    url: "https://www.xiaohongshu.com/explore/69a163ac000000002602f45d",
  }),
];
