import { assetPath } from "./assets";

export const tabs = [
  { value: "overview", label: "行程总览", short: "总览", icon: "route" },
  { value: "south", label: "南岛行程", short: "南岛", icon: "terrain" },
  { value: "north", label: "北岛行程", short: "北岛", icon: "shopping" },
  { value: "car", label: "租车规划", short: "租车", icon: "car" },
  { value: "booking", label: "机票酒店", short: "预订", icon: "hotel" },
  { value: "notes", label: "注意事项", short: "提醒", icon: "notes" },
];

export const stats = [
  { label: "出发日期", value: "9月28日", note: "深圳 → 吉隆坡 → 奥克兰" },
  { label: "返程日期", value: "10月11日", note: "奥克兰 → 深圳" },
  { label: "南岛租车", value: "待核验", note: "9月29日皇后镇取 · 10月8日基督城还" },
];

export const mapStops = [
  { tag: "SZX", name: "深圳机场", date: "9/28 · 10/12", desc: "国际航班起点与返程终点", color: "#6f8fb5", position: [22.6393, 113.8107] },
  { tag: "KUL", name: "吉隆坡转机", date: "9/28", desc: "马来西亚转机节点", color: "#7b8f6a", position: [2.7456, 101.7072] },
  { tag: "AKL", name: "奥克兰机场", date: "9/28 · 10/8 · 10/10", desc: "机场酒店、国内抵达与国际返程", color: "#f2b86b", position: [-37.0082, 174.785] },
  { tag: "AKC", name: "奥克兰市中心", date: "10/8—10/10", desc: "同一酒店连住2晚；霍比屯大巴与返程前半日", color: "#d49a63", position: [-36.8509, 174.7645] },
  { tag: "ZQN", name: "皇后镇", date: "9/29—10/3", desc: "连住4晚，格林诺奇与 Walter Peak", color: "#df7659", position: [-45.0312, 168.6626] },
  { tag: "WTP", name: "Walter Peak", date: "10/2", desc: "湖上巡游、高地农场烧烤与农场表演", color: "#f2b86b", position: [-45.1043, 168.5817] },
  { tag: "MFN", name: "米尔福德峡湾", date: "备选", desc: "高强度备选，巴士 + 游船约12—13小时", color: "#6f8fb5", position: [-44.6414, 167.8974] },
  { tag: "WKA", name: "瓦纳卡", date: "10/3—10/5", desc: "连住2晚，湖边与轻步道", color: "#8ab59b", position: [-44.698, 169.136] },
  { tag: "AOR", name: "库克山", date: "10/5", desc: "直升机冰川降落 + Big Sky 观星", color: "#7895b2", position: [-43.735, 170.0967] },
  { tag: "TEK", name: "特卡波湖 · Tekapo", date: "10/6", desc: "前往奥马鲁途中的教堂、湖边与午餐短停", color: "#8c73b8", position: [-44.0047, 170.4771] },
  { tag: "OAM", name: "奥马鲁 · Ōamaru", date: "10/6—10/7", desc: "主线住宿1晚；20:00 小蓝企鹅归巢，港边有机会看到新西兰海狗", color: "#357b73", position: [-45.0966, 170.9714] },
  { tag: "KAT", name: "Kātiki Point", date: "仅作加码备选", desc: "海狗较稳定、黄眼企鹅仅概率；07:30—17:30 开放", color: "#587f68", position: [-45.3919, 170.8662], optional: true },
  { tag: "CHC", name: "基督城与机场", date: "10/7—10/8", desc: "市中心住1晚；10月8日按更新订单还车，具体时刻与新金额待确认", color: "#9d7f66", position: [-43.4894, 172.5322] },
  { tag: "HBT", name: "霍比屯", date: "10/9", desc: "GreatSights GS10H 奥克兰往返大巴日游", color: "#9dbb54", position: [-37.8576, 175.6792] },
];

export const gallery = [
  { src: assetPath("images/queenstown.webp"), alt: "皇后镇与瓦卡蒂普湖", kicker: "SOUTH ISLAND", title: "皇后镇 · 湖与山之间" },
  { src: assetPath("images/milford.webp"), alt: "米尔福德峡湾群山与水面", kicker: "OPTIONAL", title: "米尔福德 · 高强度备选" },
  { src: assetPath("images/aoraki.webp"), alt: "普卡基湖远望奥拉基库克山", kicker: "MACKENZIE", title: "库克山 · 直升机与星空" },
  { src: assetPath("images/auckland.webp"), alt: "奥克兰市中心天际线", kicker: "NORTH ISLAND", title: "奥克兰 · 霍比屯往返落脚地" },
];

export const experienceHighlights = [
  {
    date: "10月2日",
    title: "Walter Peak 湖上巡游＋高地农场烧烤",
    desc: "主行程改为全天不用开车的湖上巡游、烧烤和农场表演，整体约3.5—4小时。",
    tag: "主方案",
    color: "#f2b86b",
    link: "https://www.realnz.com/en/experiences/tss-earnslaw-walter-peak-experiences/walter-peak-gourmet-bbq-dining/",
  },
  {
    date: "10月2日",
    title: "米尔福德峡湾保留为高强度备选",
    desc: "如果临时仍想去，可恢复 Queenstown 出发的巴士＋游船；往返约12—13小时，不再作为必须项。",
    tag: "备选",
    color: "#6f8fb5",
    link: "https://www.realnz.com/en/experiences/day-cruises/milford-sound-day-trip-from-queenstown/",
  },
  {
    date: "10月5日",
    title: "库克山直升机冰川降落＋Big Sky 观星",
    desc: "15:30 前后 Glacier Highlights 直升机，夜里 Big Sky Stargazing；天气取消时优先改期或退款。",
    tag: "重点",
    color: "#7895b2",
    link: "https://www.mtcookskiplanes.com/flights-and-tours/glacier-highlights/",
  },
];

export const southDays = [
  {
    date: "9月28日",
    weekday: "周一",
    calendarRegion: "transit",
    title: "深圳 → 吉隆坡 → 奥克兰",
    subtitle: "马来西亚转机，落地后直接休息",
    stay: "住宿 · Novotel Auckland Airport；国际航站楼门口，当天不进市区。",
    intensity: "低",
    color: "#347e90",
    events: [
      ["出发前", "深圳机场值机、托运行李"],
      ["02:45", "MH0523 深圳 → 吉隆坡"],
      ["06:45", "抵达吉隆坡 T1，转机 2小时15分"],
      ["09:00", "MH0133 吉隆坡 T1 → 奥克兰"],
      ["23:50", "抵达奥克兰"],
      ["约01:00", "完成入境、取行李"],
      ["01:15", "步行入住机场酒店"],
    ],
  },
  {
    date: "9月29日",
    weekday: "周二",
    calendarRegion: "south",
    title: "奥克兰 → 皇后镇",
    subtitle: "NZ619 与南岛取车",
    stay: "住宿 · Holiday Inn Queenstown Remarkables Park；当前采用已确认纯特大床房型，去镇中心需开车。",
    intensity: "中",
    color: "#df7659",
    events: [
      ["09:45", "前往国内航站楼"],
      ["11:35", "NZ619 起飞"],
      ["13:30", "抵达、机场午餐"],
      ["15:30", "Budget 取车（已预订）"],
      ["16:15", "入住、湖边散步"],
    ],
  },
  {
    date: "9月30日",
    weekday: "周三",
    calendarRegion: "south",
    title: "皇后镇市区",
    subtitle: "花园、湖边与 Skyline",
    stay: "住宿 · Holiday Inn Queenstown Remarkables Park；去花园、湖边与 Skyline 需开车并安排停车。",
    intensity: "低",
    color: "#8ab59b",
    events: [
      ["10:30", "皇后镇花园、湖边"],
      ["12:30", "市区午餐"],
      ["14:00", "Skyline 缆车"],
      ["16:30", "咖啡、逛街"],
      ["18:30", "晚餐"],
    ],
  },
  {
    date: "10月1日",
    weekday: "周四",
    calendarRegion: "south",
    title: "皇后镇 ⇄ 格林诺奇",
    subtitle: "湖岸公路半日游",
    stay: "住宿 · Holiday Inn Queenstown Remarkables Park；当天除格林诺奇往返外还需计算机场片区进出城。",
    intensity: "中",
    color: "#7895b2",
    events: [
      ["10:00", "皇后镇出发"],
      ["10:30", "Bob’s Cove"],
      ["11:15", "Bennett’s Bluff"],
      ["12:00", "格林诺奇午餐"],
      ["13:30", "Lagoon 木栈道"],
      ["16:30", "回到皇后镇"],
    ],
  },
  {
    date: "10月2日",
    weekday: "周五",
    calendarRegion: "south",
    title: "Walter Peak 湖上巡游",
    subtitle: "高地农场烧烤 + 农场表演",
    stay: "住宿 · Holiday Inn Queenstown Remarkables Park；Walter Peak 当天需驾车到镇中心并预留停车。",
    intensity: "低",
    color: "#f2b86b",
    highlight: "米尔福德峡湾改为高强度备选；这天主打轻松、不早起。",
    links: [
      ["Walter Peak 主方案", "https://www.realnz.com/en/experiences/tss-earnslaw-walter-peak-experiences/walter-peak-gourmet-bbq-dining/"],
      ["米尔福德备选", "https://www.realnz.com/en/experiences/day-cruises/milford-sound-day-trip-from-queenstown/"],
    ],
    events: [
      ["09:30", "慢早餐、湖边散步"],
      ["11:00", "皇后镇花园或自由逛街"],
      ["中午前后", "步行到 Steamer Wharf，按预订场次办理登船"],
      ["约4小时", "瓦卡蒂普湖往返巡游、Walter Peak 烧烤与农场表演"],
      ["傍晚", "返回皇后镇，自由喝咖啡或回酒店"],
      ["19:00", "简单晚餐"],
    ],
    alternative: {
      title: "高强度备选 · 米尔福德峡湾巴士＋游船",
      desc: "若临时仍想去，可恢复 06:45 左右出发、20:00 左右返回的 12—13 小时方案；往返坐车约9—10小时。",
    },
  },
  {
    date: "10月3日",
    weekday: "周六",
    calendarRegion: "south",
    title: "皇后镇 → 箭镇 → 瓦纳卡",
    subtitle: "Crown Range 与 Cardrona",
    stay: "住宿 · Wanaka Luxury Apartments；坏天气改走 Cromwell。",
    intensity: "中",
    color: "#df7659",
    events: [
      ["10:00", "退房出发"],
      ["10:30", "箭镇、午餐"],
      ["13:00", "前往瓦纳卡"],
      ["13:45", "Crown Range 观景"],
      ["14:30", "Cardrona 咖啡"],
      ["16:00", "抵达瓦纳卡"],
    ],
  },
  {
    date: "10月4日",
    weekday: "周日",
    calendarRegion: "south",
    title: "瓦纳卡",
    subtitle: "整日不换酒店",
    stay: "住宿 · Wanaka Luxury Apartments；下午项目按天气决定。",
    intensity: "低",
    color: "#8ab59b",
    events: [
      ["10:30", "湖边、That Wanaka Tree"],
      ["12:30", "午餐"],
      ["14:00", "Puzzling World 或 Mount Iron"],
      ["16:30", "咖啡、看日落"],
      ["18:30", "晚餐"],
    ],
  },
  {
    date: "10月5日",
    weekday: "周一",
    calendarRegion: "south",
    title: "瓦纳卡 → 库克山",
    subtitle: "直升机冰川降落 + Big Sky 星空",
    stay: "住宿 · 已预订 The Hermitage · Mt Cook Motel Studio Queen；含双人早餐，确认号已私下保存，10月入住到 Mt Cook Lodge 办理入住。",
    intensity: "高",
    color: "#7895b2",
    highlight: "直升机参考 NZ$649/成人，2人约 NZ$1,298；Big Sky 成人 NZ$159 起，2人约 NZ$318。",
    links: [
      ["Glacier Highlights 直升机", "https://www.mtcookskiplanes.com/flights-and-tours/glacier-highlights/"],
      ["Big Sky Stargazing", "https://www.hermitage.co.nz/experience/big-sky-stargazing/"],
      ["天气取消政策", "https://www.mtcookskiplanes.com/faq/"],
    ],
    events: [
      ["08:45", "退房出发"],
      ["10:15", "Lindis Pass 观景"],
      ["11:15", "Omarama 午餐、加油"],
      ["13:30", "Lake Pukaki 短停"],
      ["14:15", "先到库克山机场办理直升机报到"],
      ["15:30前后", "Glacier Highlights 直升机，45分钟含约10—15分钟冰川降落"],
      ["17:00", "在库克山用餐、补充保暖衣物"],
      ["19:00", "Big Sky 前休息；活动后返回已预订的 Mt Cook Motel"],
      ["21:30前后", "Big Sky Stargazing 观星，约75—90分钟"],
    ],
    alternative: {
      title: "天气与体力备选",
      desc: "直升机可移到10月6日早班；观星可改为酒店外自助看星。10月5日处在下弦月后、新月前，前半夜月光干扰较小。",
    },
  },
  {
    date: "10月6日",
    weekday: "周二",
    calendarRegion: "south",
    title: "库克山 → 蒂卡波 → 奥马鲁",
    subtitle: "蒂卡波短停 + 20:00 小蓝企鹅归巢",
    stay: "住宿 · 奥马鲁，酒店或民宿待确认；次日继续自驾前往基督城。",
    intensity: "高",
    color: "#123f36",
    events: [
      ["08:30", "仅在前一日停飞时，候补直升机首班"],
      ["10:00", "最晚离开库克山"],
      ["11:30", "抵达蒂卡波，教堂、湖边、午餐"],
      ["13:00", "从蒂卡波出发前往奥马鲁"],
      ["15:30", "抵达奥马鲁、办理入住"],
      ["16:30", "奥马鲁港边步道找新西兰海狗；保持至少20米，不喂、不摸、不挡住海狗与海之间的路线"],
      ["18:00", "提前吃晚餐，准备企鹅晚场"],
      ["19:30", "提前30分钟抵达 Ōamaru Blue Penguin Colony；晚场禁止拍照、录像及亮屏"],
      ["20:00", "小蓝企鹅归巢：General 成人 NZD 50、Premium 成人 NZD 70（2026-07-29核验；预订时重新确认余量）"],
      ["活动后", "返回奥马鲁住宿休息"],
    ],
    alternative: {
      title: "可选加码 · Kātiki Point",
      desc: "仅在天气、体力和时间都充足时考虑；它不属于正式主线，不能影响19:30抵达小蓝企鹅保护区。",
    },
  },
  {
    date: "10月7日",
    weekday: "周三",
    calendarRegion: "south",
    title: "奥马鲁 → 基督城",
    subtitle: "海岸线北上 + 基督城傍晚慢游",
    stay: "住宿 · 基督城市中心，1晚；酒店待确认，租车保留至10月8日并按更新订单还车。",
    intensity: "中",
    color: "#9d7f66",
    events: [
      ["09:30", "奥马鲁退房，驾车前往基督城"],
      ["10:45", "Timaru 海边或咖啡短休"],
      ["12:30", "Ashburton 午餐并让驾驶员休息"],
      ["14:30", "抵达基督城市中心，停车并办理入住"],
      ["15:30", "Riverside Market、雅芳河畔"],
      ["17:00", "Cathedral Square、New Regent Street"],
      ["18:30", "基督城市区晚餐"],
    ],
  },
  {
    date: "10月8日",
    weekday: "周四",
    calendarRegion: "south",
    title: "基督城 → 奥克兰",
    subtitle: "城市半日 + 按更新订单还车 + 晚班JQ242",
    stay: "住宿 · 奥克兰市中心连续第1晚；抵达后直接进城，次日 07:00 须到 SkyCity Coach Terminal 报到。",
    intensity: "中",
    color: "#df7659",
    events: [
      ["09:00", "酒店退房并寄存行李"],
      ["09:30", "纸板教堂、Latimer Square 与市中心自由活动"],
      ["12:30", "午餐、最后逛街或咖啡；14:15 返回酒店取行李"],
      ["下午 · 待确认", "按新确认邮件安排出发，驾车前往基督城机场；途中预留加油与道路缓冲"],
      ["下午", "Budget 基督城机场还车（已修改到10月8日；具体时刻、新总价与条款待新确认邮件核验）"],
      ["还车后", "进入国内航站楼，不再返回市区"],
      ["18:30左右", "值机开放后办理手续并预留晚点缓冲"],
      ["20:30", "JQ242 基督城 → 奥克兰；Google Flights 2026-07-29 快照为 NZD 156/人起，通常可能晚点30分钟以上；行李等可选费用与最终价格须在捷星官网结账核验"],
      ["21:50", "计划抵达奥克兰，随后前往奥克兰市中心酒店"],
    ],
  },
];

export const northDays = [
  {
    date: "10月9日",
    weekday: "周五",
    calendarRegion: "north",
    title: "奥克兰 ⇄ 霍比屯",
    subtitle: "GreatSights GS10H 大巴日游",
    stay: "住宿 · 返回同一间奥克兰市中心酒店，连续第2晚；不退房、不换酒店、不租车。",
    intensity: "中",
    color: "#9dbb54",
    events: [
      ["07:00", "SkyCity Coach Terminal 报到"],
      ["07:15", "大巴前往霍比屯"],
      ["09:30", "抵达 The Shire’s Rest"],
      ["09:30—13:15", "霍比屯游览"],
      ["13:15", "大巴返回奥克兰"],
      ["15:30", "抵达 SkyCity Coach Terminal"],
      ["15:45起", "送回指定奥克兰市中心酒店"],
    ],
  },
  {
    date: "10月10日",
    weekday: "周六",
    calendarRegion: "north",
    title: "奥克兰半日 → 奥克兰机场",
    subtitle: "寄存行李、轻松半日与国际返程",
    stay: "当晚不住酒店；上午从市中心酒店退房后寄存行李，下午前往奥克兰机场等待次日凌晨航班。",
    intensity: "低",
    color: "#f2b86b",
    events: [
      ["09:00", "市中心酒店退房并寄存行李"],
      ["09:30—13:00", "奥克兰轻松半日"],
      ["13:00", "午餐、返回酒店取行李"],
      ["15:30", "前往奥克兰机场"],
      ["16:30", "抵达国际航站楼、寄存或整理行李"],
      ["21:45", "办理国际值机"],
    ],
  },
  {
    date: "10月11日",
    weekday: "周日",
    calendarRegion: "transit",
    title: "奥克兰 → 深圳",
    subtitle: "国际航班返程",
    stay: "住宿 · 机上；购物品提前整理托运，不要把液体留在手提行李。",
    intensity: "低",
    color: "#347e90",
    events: [
      ["00:30", "前往登机口"],
      ["01:25", "MH0132 奥克兰 → 吉隆坡，07:55 抵达 T1"],
      ["21:05", "MH0522 吉隆坡 T1 → 深圳，次日 01:15 抵达"],
    ],
  },
];

export const shoppingStops = [
  ["09:00", "市中心酒店出发", "步行前往 Queen Street 与 Britomart"],
  ["10:00", "Queen Street", "市中心主购物街，顺路走到 Britomart"],
  ["12:30", "Commercial Bay", "午餐 + 品牌店，不用来回赶"],
  ["14:00", "Westfield Newmarket", "百货、美妆、服装集中采购"],
  ["18:00", "晚餐", "Newmarket 或市中心用餐"],
  ["19:30", "返回市中心酒店", "整理购物品，第二天从 SkyCity 乘大巴往返霍比屯"],
];

export const hotelPlans = [
  {
    place: "奥克兰机场",
    date: "9月28日",
    nights: "1晚",
    label: "首选",
    name: "Novotel Auckland Airport",
    rating: "8.8 / 10",
    ratingDetail: "位置9.8 · 清洁9.3 · 舒适9.4",
    reason: "仅用于9月28日深夜国际抵达，步行入住最省力；10月8—9日改住奥克兰市中心。",
    facts: ["国际航站楼门口", "可步行转国内航站楼", "24小时前台"],
    backup: "ibis budget Auckland Airport——预算更友好，距航站楼约800米，可用机场巴士。",
    links: [
      ["首选官网", "https://all.accor.com/hotel/7485/index.en.shtml"],
      ["住客评分", "https://www.booking.com/reviews/nz/hotel/novotel-auckland-airport.en-gb.html"],
      ["备选官网", "https://all.accor.com/hotel/7865/index.en.shtml"],
    ],
  },
  {
    place: "皇后镇",
    date: "9月29日—10月2日",
    nights: "4晚",
    label: "首选",
    name: "Holiday Inn Queenstown Remarkables Park",
    rating: "8.8 / 10",
    ratingDetail: "28 m²山景特大床 · 四晚可取消总价NZD 1,356",
    reason: "当前唯一同时核验到纯特大床、四晚总价和完整取消付款条款的低价方案；代价是距镇中心约6.8公里。",
    facts: ["纯特大床", "可取消且无需预付", "距镇中心约6.8公里"],
    backup: "The Rees——湖景特大床、免费停车和镇中心接驳，但四晚总价明显更高；Summit Serenity Airbnb 湖景更强。",
    links: [
      ["首选官网", "https://www.ihg.com/holidayinn/hotels/us/en/queenstown/zqnrm/hoteldetail"],
      ["住客评分", "https://www.booking.com/hotel/nz/holiday-inn-queenstown-remarkables-park.html"],
      ["备选官网", "https://www.therees.co.nz/"],
    ],
  },
  {
    place: "瓦纳卡",
    date: "10月3—4日",
    nights: "2晚",
    label: "首选",
    name: "Wanaka Luxury Apartments",
    rating: "9.0 / 10",
    ratingDetail: "位置9.1 · 59 m² · 两晚可取消总价NZD 660",
    reason: "距湖岸600米，59 m²一卧室大床公寓带厨房、Spa浴缸和免费停车；比精确日期无房的Edgewater更可执行。",
    facts: ["步行约10分钟到湖边", "免费停车", "大床公寓带厨房"],
    backup: "West Meadows of Wanaka——35 m²特大床一室公寓、评分9.2，但步行湖边不如首选。",
    links: [
      ["首选官网", "https://www.wanakaluxuryapartments.co.nz/"],
      ["住客评分", "https://www.booking.com/hotel/nz/wanaka-luxury-apartments.html"],
      ["备选官网", "https://westmeadowswanaka.co.nz/"],
    ],
  },
  {
    place: "奥拉基 / 库克山",
    date: "10月5日",
    nights: "1晚",
    label: "已预订",
    name: "The Hermitage · Mt Cook Motel Studio Queen",
    rating: "官网已确认",
    ratingDetail: "确认号已私下保存 · 含双人早餐 · 已支付NZD 504",
    reason: "冬宫官网预订已确认；住在库克山村内，避免 Big Sky 后夜间驾驶回 Twizel，并保留次晨直升机天气候补的便利。10月入住需到 Mt Cook Lodge 办理入住。",
    facts: ["确认号已私下保存", "Queen床与完整厨房", "含双人早餐", "免费停车", "入住前48小时以外可取消"],
    backup: "如主动取消后需要替代，可重新核验 Omahau Down、Pukaki / Twizel 民宿的即时库存。",
    links: [
      ["冬宫含早套餐", "https://book.hermitage.co.nz/onecart/wbe/room/20104/hermitage/2026-10-05/2026-10-06/BBSAVE10/2"],
      ["Mt Cook Motels 官网说明", "https://www.hermitage.co.nz/stay/mt-cook-motels/"],
      ["Booking备选", "https://www.booking.com/hotel/nz/omahau-down.html"],
    ],
  },
  {
    place: "基督城",
    date: "10月7日",
    nights: "1晚",
    label: "待重核",
    name: "Novotel Christchurch Cathedral Square",
    rating: "8.2 / 10",
    ratingDetail: "位置9.6 · 31 m²纯King · 当前日期价格待重新核验",
    reason: "第二天上午的 New Regent Street、Riverside Market 与植物园可从 Cathedral Square 直接步行串联；旧的10月6—7日价格不能顺延到新的10月7—8日。",
    facts: ["Cathedral Square", "24小时前台", "纯特大床", "约20—25分钟车程到机场"],
    backup: "Distinction Christchurch——位置评分9.7、经典King可取消NZD 435；Rydges停车费用更明确，但步行Riverside Market约15分钟。",
    links: [
      ["首选官网", "https://all.accor.com/hotel/6592/index.en.shtml"],
      ["住客评分", "https://www.booking.com/hotel/nz/novotel-christchurch-cathedral-square.zh-cn.html"],
      ["备选官网", "https://www.distinctionhotelschristchurch.co.nz/"],
    ],
  },
];

export const bookingItems = [
  ["flight-nz619", "NZ619 奥克兰→皇后镇", "9月29日11:35—13:30；确认托运行李。"],
  ["south-car", "Budget 南岛租车 · 已改到10月8日还车", "9月29日皇后镇机场取车；还车日期已改为10月8日。具体还车时刻、新总价、车型、保障与退改条款须以新确认邮件为准，旧订单的8天总价和条款不再作为现行信息。"],
  ["hotel-airport", "奥克兰机场酒店", "仅9月28日1晚；首选 Novotel Auckland Airport。"],
  ["hotel-auckland-city", "奥克兰市中心住宿 · 2晚价格待重核", "10月8日晚入住、10月10日退房，连续2晚；旧的10月7—9日两晚总价日期不同，不能沿用，须重新核验精确日期价格。"],
  ["hotel-queenstown", "皇后镇住宿", "9月29日入住4晚；当前首选已核验纯特大床的 Holiday Inn Remarkables Park。"],
  ["hotel-wanaka", "瓦纳卡住宿", "10月3日入住2晚；首选 Wanaka Luxury Apartments。"],
  ["mount-cook", "库克山住宿", "已预订：The Hermitage · Mt Cook Motel Studio Queen，10月5日1晚，含双人早餐，确认号已私下保存，已支付 NZD 504。"],
  ["mount-cook-helicopter", "库克山直升机", "10月5日15:30前后；Glacier Highlights 约45分钟，2人参考 NZ$1,298，确认天气取消可退款。"],
  ["mount-cook-stargazing", "Big Sky Stargazing 观星", "10月5日晚较晚场；约75—90分钟，2人 NZ$318 起，可询问中文讲解。"],
  ["hotel-christchurch", "基督城住宿 · 1晚待预订", "10月7日入住、10月8日退房；优先市中心步行位置，所有旧日期价格均不能沿用，须重新核验精确日期库存与总价。"],
  ["oamaru-stay-penguins", "奥马鲁住宿 + 小蓝企鹅晚场 · 待预订", "主行程：10月6日住奥马鲁并参加20:00官方小蓝企鹅晚场。General 2人NZD 100、Premium 2人NZD 140为2026-07-29核验价格；住宿和企鹅票均尚未预订，付款前重新确认库存、总价与退改规则。"],
  ["walter-peak", "Walter Peak 湖上巡游 + 高地农场烧烤", "10月2日；优先选择中午或下午较早场，全程约3.5—4小时。"],
  ["flight-jq242", "JQ242 基督城→奥克兰 · 待预订", "10月8日20:30—21:50；Google Flights 显示 NZD 156/人起，2人基础 NZD 312，行李另计；须在捷星官网核验并预订。"],
  ["north-car-cancel", "北岛租车订单 · 待用户取消", "已存在真实 Budget 订单；现行程不再取车，但修改本页面不等于取消订单。请在 Budget 官网管理订单中主动取消并保存确认。"],
  ["hobbiton", "GreatSights 霍比屯大巴日游 · 待预订", "10月9日 GS10H 已核验可选：07:00 SkyCity Coach Terminal 报到，07:15出发，约15:30返回；NZD 259/成人，2人标价NZD 518，支付页附加费未知；提前2小时免费取消。"],
];

export const notes = [
  {
    title: "道路与天气",
    items: [
      "每天早晨查看 NZTA 实时路况。",
      "Crown Range 若积雪或封路，改走 Cromwell 路线。",
      "直升机与户外观星都看天气：10月5日白天确认飞行，傍晚再确认观星；取消时以改期或退款为先。",
      "南岛避免夜间驾驶；雪链随车携带。",
    ],
  },
  {
    title: "航班与行李",
    items: [
      "Jetstar 基础票通常只含合计 7kg 手提行李。",
      "两段国内航班都要在付款前确认托运行李。",
      "10月10日购物品提前分配到托运行李。",
    ],
  },
  {
    title: "租车关键点",
    items: [
      "南岛 Budget 订单已把还车日期改到10月8日；预订代码已私下保存。",
      "9月29日皇后镇机场取车，10月8日基督城机场还车；具体还车时刻须以新确认邮件为准。",
      "改期后的新总价、计费时长、车型、保障、付款与退改规则尚未核验；旧订单的NZ$2,052.96和旧条款仅是历史信息，不能作为现行承诺。",
      "北岛 Budget 订单现为待取消：网站改成大巴行程不会同步取消真实订单，需在 Budget 官网管理订单中主动操作并保存取消确认。",
      "不走 Skippers Road；车顶、底盘、涉水及其他条款除外损失仍可能需要全额自付。",
    ],
  },
];
