import { assetPath } from "./assets";

export const tabs = [
  { value: "overview", label: "行程总览", short: "总览", icon: "route" },
  { value: "south", label: "南岛行程", short: "南岛", icon: "terrain" },
  { value: "north", label: "北岛行程", short: "北岛", icon: "shopping" },
  { value: "car", label: "租车规划", short: "租车", icon: "car" },
  { value: "booking", label: "酒店预订", short: "酒店", icon: "hotel" },
  { value: "activities", label: "活动预订", short: "活动", icon: "activity" },
  { value: "notes", label: "注意事项", short: "提醒", icon: "notes" },
];

export const stats = [
  { label: "出发日期", value: "9月28日", note: "深圳 → 吉隆坡 → 奥克兰" },
  { label: "返程日期", value: "10月11日", note: "奥克兰 → 深圳" },
  { label: "南岛租车", value: "已预订", note: "9月29日11:00皇后镇取 · 10月8日11:00基督城还" },
];

export const mapStops = [
  { tag: "SZX", name: "深圳机场", date: "9/28 · 10/12", desc: "国际航班起点与返程终点", color: "#6f8fb5", position: [22.6393, 113.8107] },
  { tag: "KUL", name: "吉隆坡转机", date: "9/28", desc: "马来西亚转机节点", color: "#7b8f6a", position: [2.7456, 101.7072] },
  { tag: "AKL", name: "奥克兰机场", date: "9/28—9/29 · 10/8 · 10/10", desc: "国际抵达后机场过夜候机、国内航班与国际返程", color: "#f2b86b", position: [-37.0082, 174.785] },
  { tag: "AKC", name: "奥克兰市中心", date: "10/8—10/10", desc: "同一酒店连住2晚；霍比屯大巴与返程前半日", color: "#d49a63", position: [-36.8509, 174.7645] },
  { tag: "ZQN", name: "皇后镇", date: "9/29—10/3", desc: "连住4晚，格林诺奇与 Walter Peak", color: "#df7659", position: [-45.0312, 168.6626] },
  { tag: "WTP", name: "Walter Peak", date: "10/2", desc: "湖上巡游、高地农场烧烤与农场表演", color: "#f2b86b", position: [-45.1043, 168.5817] },
  { tag: "MFN", name: "米尔福德峡湾", date: "备选", desc: "高强度备选，巴士 + 游船约12—13小时", color: "#6f8fb5", position: [-44.6414, 167.8974] },
  { tag: "WKA", name: "瓦纳卡", date: "10/3—10/5", desc: "连住2晚，湖边与轻步道", color: "#8ab59b", position: [-44.698, 169.136] },
  { tag: "AOR", name: "库克山", date: "10/5", desc: "直升机冰川降落 + Big Sky 观星", color: "#7895b2", position: [-43.735, 170.0967] },
  { tag: "TEK", name: "特卡波湖 · Tekapo", date: "10/6", desc: "前往奥马鲁途中的教堂、湖边与午餐短停", color: "#8c73b8", position: [-44.0047, 170.4771] },
  { tag: "OAM", name: "奥马鲁 · Ōamaru", date: "10/6—10/7", desc: "主线住宿1晚；20:00 小蓝企鹅归巢，港边有机会看到新西兰海狗", color: "#357b73", position: [-45.0966, 170.9714] },
  { tag: "KAT", name: "Kātiki Point", date: "仅作加码备选", desc: "海狗较稳定、黄眼企鹅仅概率；07:30—17:30 开放", color: "#587f68", position: [-45.3919, 170.8662], optional: true },
  { tag: "CHC", name: "基督城与机场", date: "10/7—10/8", desc: "市中心住1晚；10月8日11:00机场还车，13:50乘JQ236飞奥克兰", color: "#9d7f66", position: [-43.4894, 172.5322] },
  { tag: "HBT", name: "霍比屯", date: "10/9", desc: "GreatSights GS10H 奥克兰往返大巴日游", color: "#9dbb54", position: [-37.8576, 175.6792] },
];

export const gallery = [
  { src: assetPath("images/queenstown.webp"), alt: "皇后镇与瓦卡蒂普湖", kicker: "SOUTH ISLAND", title: "皇后镇 · 湖与山之间" },
  { src: assetPath("images/milford.webp"), alt: "米尔福德峡湾群山与水面", kicker: "OPTIONAL", title: "米尔福德 · 高强度备选" },
  { src: assetPath("images/aoraki.webp"), alt: "普卡基湖远望奥拉基库克山", kicker: "MACKENZIE", title: "库克山 · 直升机与星空" },
  { src: assetPath("images/auckland.webp"), alt: "奥克兰市中心天际线", kicker: "NORTH ISLAND", title: "奥克兰 · 霍比屯往返落脚地" },
];

export const experienceHighlights = [
  {
    date: "10月2日",
    title: "Walter Peak 湖上巡游＋高地农场烧烤",
    desc: "主行程改为全天不用开车的湖上巡游、烧烤和农场表演，整体约3.5—4小时。",
    tag: "主方案",
    color: "#f2b86b",
    link: "https://www.realnz.com/en/experiences/tss-earnslaw-walter-peak-experiences/walter-peak-gourmet-bbq-dining/",
  },
  {
    date: "10月2日",
    title: "米尔福德峡湾保留为高强度备选",
    desc: "如果临时仍想去，可恢复 Queenstown 出发的巴士＋游船；往返约12—13小时，不再作为必须项。",
    tag: "备选",
    color: "#6f8fb5",
    link: "https://www.realnz.com/en/experiences/day-cruises/milford-sound-day-trip-from-queenstown/",
  },
  {
    date: "10月5日",
    title: "库克山直升机冰川降落＋Big Sky 观星",
    desc: "15:30 前后 Glacier Highlights 直升机，夜里 Big Sky Stargazing；天气取消时优先改期或退款。",
    tag: "重点",
    color: "#7895b2",
    link: "https://www.mtcookskiplanes.com/flights-and-tours/glacier-highlights/",
  },
];

export const southDays = [
  {
    date: "9月28日",
    weekday: "周一",
    calendarRegion: "transit",
    title: "深圳 → 吉隆坡 → 奥克兰",
    subtitle: "马来西亚转机，落地后留在机场候早班机",
    stay: "当晚不住酒店；完成入境与取行李后留在机场休息，次日上午乘 JQ295 前往皇后镇。",
    intensity: "低",
    color: "#347e90",
    events: [
      ["出发前", "深圳机场值机、托运行李"],
      ["02:45", "MH0523 深圳 → 吉隆坡"],
      ["06:45", "抵达吉隆坡 T1，转机 2小时15分"],
      ["09:00", "MH0133 吉隆坡 T1 → 奥克兰"],
      ["23:50", "抵达奥克兰"],
      ["约01:00", "完成入境、取行李"],
      ["01:15", "留在奥克兰机场过夜候机，不办理酒店入住"],
    ],
  },
  {
    date: "9月29日",
    weekday: "周二",
    calendarRegion: "south",
    title: "奥克兰 → 皇后镇",
    subtitle: "JQ295 早班机 + 11:00南岛取车",
    stay: "住宿 · 皇后镇已订房源；15:00 后办理入住，具体位置与入户信息私下保存。",
    intensity: "中",
    color: "#df7659",
    events: [
      ["06:15", "前往奥克兰机场国内航站楼 D"],
      ["07:00", "完成值机与安检，按出票信息前往登机口"],
      ["08:15", "JQ295 奥克兰 → 皇后镇（电子客票状态 OK）"],
      ["10:10", "抵达皇后镇机场"],
      ["11:00", "Budget 皇后镇机场取车（已预订）"],
      ["11:30", "取车后前往酒店寄存行李，再安排午餐与湖边散步"],
    ],
  },
  {
    date: "9月30日",
    weekday: "周三",
    calendarRegion: "south",
    title: "皇后镇市区",
    subtitle: "花园、湖边与 Skyline",
    stay: "住宿 · 皇后镇已订房源；前往花园、湖边与 Skyline 的实际车程以导航为准。",
    intensity: "低",
    color: "#8ab59b",
    events: [
      ["10:30", "皇后镇花园、湖边"],
      ["12:30", "市区午餐"],
      ["14:00", "Skyline 缆车"],
      ["16:30", "咖啡、逛街"],
      ["18:30", "晚餐"],
    ],
  },
  {
    date: "10月1日",
    weekday: "周四",
    calendarRegion: "south",
    title: "皇后镇 ⇄ 格林诺奇",
    subtitle: "湖岸公路半日游",
    stay: "住宿 · 皇后镇已订房源；格林诺奇往返的出发时间以当天导航为准。",
    intensity: "中",
    color: "#7895b2",
    events: [
      ["10:00", "皇后镇出发"],
      ["10:30", "Bob’s Cove"],
      ["11:15", "Bennett’s Bluff"],
      ["12:00", "格林诺奇午餐"],
      ["13:30", "Lagoon 木栈道"],
      ["16:30", "回到皇后镇"],
    ],
  },
  {
    date: "10月2日",
    weekday: "周五",
    calendarRegion: "south",
    title: "Walter Peak 湖上巡游",
    subtitle: "高地农场烧烤 + 农场表演",
    stay: "住宿 · 皇后镇已订房源；Walter Peak 当天按导航前往镇中心并预留停车。",
    intensity: "低",
    color: "#f2b86b",
    highlight: "米尔福德峡湾改为高强度备选；这天主打轻松、不早起。",
    links: [
      ["Walter Peak 主方案", "https://www.realnz.com/en/experiences/tss-earnslaw-walter-peak-experiences/walter-peak-gourmet-bbq-dining/"],
      ["米尔福德备选", "https://www.realnz.com/en/experiences/day-cruises/milford-sound-day-trip-from-queenstown/"],
    ],
    events: [
      ["09:30", "慢早餐、湖边散步"],
      ["11:00", "皇后镇花园或自由逛街"],
      ["中午前后", "步行到 Steamer Wharf，按预订场次办理登船"],
      ["约4小时", "瓦卡蒂普湖往返巡游、Walter Peak 烧烤与农场表演"],
      ["傍晚", "返回皇后镇，自由喝咖啡或回酒店"],
      ["19:00", "简单晚餐"],
    ],
    alternative: {
      title: "高强度备选 · 米尔福德峡湾巴士＋游船",
      desc: "若临时仍想去，可恢复 06:45 左右出发、20:00 左右返回的 12—13 小时方案；往返坐车约9—10小时。",
    },
  },
  {
    date: "10月3日",
    weekday: "周六",
    calendarRegion: "south",
    title: "皇后镇 → 箭镇 → 瓦纳卡",
    subtitle: "Crown Range 与 Cardrona",
    stay: "住宿 · Wanaka Luxury Apartments；坏天气改走 Cromwell。",
    intensity: "中",
    color: "#df7659",
    events: [
      ["10:00", "退房出发"],
      ["10:30", "箭镇、午餐"],
      ["13:00", "前往瓦纳卡"],
      ["13:45", "Crown Range 观景"],
      ["14:30", "Cardrona 咖啡"],
      ["16:00", "抵达瓦纳卡"],
    ],
  },
  {
    date: "10月4日",
    weekday: "周日",
    calendarRegion: "south",
    title: "瓦纳卡",
    subtitle: "整日不换酒店",
    stay: "住宿 · Wanaka Luxury Apartments；下午项目按天气决定。",
    intensity: "低",
    color: "#8ab59b",
    events: [
      ["10:30", "湖边、That Wanaka Tree"],
      ["12:30", "午餐"],
      ["14:00", "Puzzling World 或 Mount Iron"],
      ["16:30", "咖啡、看日落"],
      ["18:30", "晚餐"],
    ],
  },
  {
    date: "10月5日",
    weekday: "周一",
    calendarRegion: "south",
    title: "瓦纳卡 → 库克山",
    subtitle: "直升机冰川降落 + Big Sky 星空",
    stay: "住宿 · 已预订 The Hermitage · Mt Cook Motel Studio Queen；含双人早餐，确认号已私下保存，10月入住到 Mt Cook Lodge 办理入住。",
    intensity: "高",
    color: "#7895b2",
    highlight: "直升机参考 NZ$649/成人，2人约 NZ$1,298；Big Sky 成人 NZ$159 起，2人约 NZ$318。",
    links: [
      ["Glacier Highlights 直升机", "https://www.mtcookskiplanes.com/flights-and-tours/glacier-highlights/"],
      ["Big Sky Stargazing", "https://www.hermitage.co.nz/experience/big-sky-stargazing/"],
      ["天气取消政策", "https://www.mtcookskiplanes.com/faq/"],
    ],
    events: [
      ["08:45", "退房出发"],
      ["10:15", "Lindis Pass 观景"],
      ["11:15", "Omarama 午餐、加油"],
      ["13:30", "Lake Pukaki 短停"],
      ["14:15", "先到库克山机场办理直升机报到"],
      ["15:30前后", "Glacier Highlights 直升机，45分钟含约10—15分钟冰川降落"],
      ["17:00", "在库克山用餐、补充保暖衣物"],
      ["19:00", "Big Sky 前休息；活动后返回已预订的 Mt Cook Motel"],
      ["21:30前后", "Big Sky Stargazing 观星，约75—90分钟"],
    ],
    alternative: {
      title: "天气与体力备选",
      desc: "直升机可移到10月6日早班；观星可改为酒店外自助看星。10月5日处在下弦月后、新月前，前半夜月光干扰较小。",
    },
  },
  {
    date: "10月6日",
    weekday: "周二",
    calendarRegion: "south",
    title: "库克山 → 蒂卡波 → 奥马鲁",
    subtitle: "蒂卡波短停 + 20:00 小蓝企鹅归巢",
    stay: "住宿 · 奥马鲁，酒店或民宿待确认；次日继续自驾前往基督城。",
    intensity: "高",
    color: "#123f36",
    events: [
      ["08:30", "仅在前一日停飞时，候补直升机首班"],
      ["10:00", "最晚离开库克山"],
      ["11:30", "抵达蒂卡波，教堂、湖边、午餐"],
      ["13:00", "从蒂卡波出发前往奥马鲁"],
      ["15:30", "抵达奥马鲁、办理入住"],
      ["16:30", "奥马鲁港边步道找新西兰海狗；保持至少20米，不喂、不摸、不挡住海狗与海之间的路线"],
      ["18:00", "提前吃晚餐，准备企鹅晚场"],
      ["19:30", "提前30分钟抵达 Ōamaru Blue Penguin Colony；晚场禁止拍照、录像及亮屏"],
      ["20:00", "小蓝企鹅归巢：General 成人 NZD 50、Premium 成人 NZD 70（2026-07-29核验；预订时重新确认余量）"],
      ["活动后", "返回奥马鲁住宿休息"],
    ],
    alternative: {
      title: "可选加码 · Kātiki Point",
      desc: "仅在天气、体力和时间都充足时考虑；它不属于正式主线，不能影响19:30抵达小蓝企鹅保护区。",
    },
  },
  {
    date: "10月7日",
    weekday: "周三",
    calendarRegion: "south",
    title: "奥马鲁 → 基督城",
    subtitle: "海岸线北上 + 基督城傍晚慢游",
    stay: "住宿 · 基督城已订房源，1晚；15:00 后入住，租车保留至10月8日11:00机场还车。",
    intensity: "中",
    color: "#9d7f66",
    events: [
      ["09:30", "奥马鲁退房，驾车前往基督城"],
      ["10:45", "Timaru 海边或咖啡短休"],
      ["12:30", "Ashburton 午餐并让驾驶员休息"],
      ["14:30", "抵达基督城市中心，停车并办理入住"],
      ["15:30", "Riverside Market、雅芳河畔"],
      ["17:00", "Cathedral Square、New Regent Street"],
      ["18:30", "基督城市区晚餐"],
    ],
  },
  {
    date: "10月8日",
    weekday: "周四",
    calendarRegion: "south",
    title: "基督城 → 奥克兰",
    subtitle: "11:00还车 + JQ236 午后航班",
    stay: "住宿 · 已订 Hotel Grand Chancellor Auckland，连续第1晚；15:10抵达后直接进城，次日 07:00 须到 SkyCity Coach Terminal 报到。",
    intensity: "中",
    color: "#df7659",
    events: [
      ["08:30", "酒店退房，早餐后取车出发"],
      ["09:30", "从基督城市中心前往机场，途中加满油并预留道路缓冲"],
      ["11:00", "Budget 基督城机场还车（已预订）"],
      ["还车后", "步行进入国内航站楼，办理值机与安检"],
      ["13:50", "JQ236 基督城 → 奥克兰（电子客票状态 OK）"],
      ["15:10", "抵达奥克兰，随后前往奥克兰市中心酒店"],
    ],
  },
];

export const northDays = [
  {
    date: "10月9日",
    weekday: "周五",
    calendarRegion: "north",
    title: "奥克兰 ⇄ 霍比屯",
    subtitle: "GreatSights GS10H 大巴日游",
    stay: "住宿 · 返回已订 Hotel Grand Chancellor Auckland，连续第2晚；不退房、不换酒店、不租车。",
    intensity: "中",
    color: "#9dbb54",
    events: [
      ["07:00", "SkyCity Coach Terminal 报到"],
      ["07:15", "大巴前往霍比屯"],
      ["09:30", "抵达 The Shire’s Rest"],
      ["09:30—13:15", "霍比屯游览"],
      ["13:15", "大巴返回奥克兰"],
      ["15:30", "抵达 SkyCity Coach Terminal"],
      ["15:45起", "送回指定奥克兰市中心酒店"],
    ],
  },
  {
    date: "10月10日",
    weekday: "周六",
    calendarRegion: "north",
    title: "奥克兰半日 → 奥克兰机场",
    subtitle: "寄存行李、轻松半日与国际返程",
    stay: "当晚不住酒店；上午从 Hotel Grand Chancellor Auckland 退房后寄存行李，下午前往奥克兰机场等待次日凌晨航班。",
    intensity: "低",
    color: "#f2b86b",
    events: [
      ["09:00", "市中心酒店退房并寄存行李"],
      ["09:30—13:00", "奥克兰轻松半日"],
      ["13:00", "午餐、返回酒店取行李"],
      ["15:30", "前往奥克兰机场"],
      ["16:30", "抵达国际航站楼、寄存或整理行李"],
      ["21:45", "办理国际值机"],
    ],
  },
  {
    date: "10月11日",
    weekday: "周日",
    calendarRegion: "transit",
    title: "奥克兰 → 深圳",
    subtitle: "国际航班返程",
    stay: "住宿 · 机上；购物品提前整理托运，不要把液体留在手提行李。",
    intensity: "低",
    color: "#347e90",
    events: [
      ["00:30", "前往登机口"],
      ["01:25", "MH0132 奥克兰 → 吉隆坡，07:55 抵达 T1"],
      ["21:05", "MH0522 吉隆坡 T1 → 深圳，次日 01:15 抵达"],
    ],
  },
];

export const shoppingStops = [
  ["09:00", "市中心酒店出发", "步行前往 Queen Street 与 Britomart"],
  ["10:00", "Queen Street", "市中心主购物街，顺路走到 Britomart"],
  ["12:30", "Commercial Bay", "午餐 + 品牌店，不用来回赶"],
  ["14:00", "Westfield Newmarket", "百货、美妆、服装集中采购"],
  ["18:00", "晚餐", "Newmarket 或市中心用餐"],
  ["19:30", "返回市中心酒店", "整理购物品，第二天从 SkyCity 乘大巴往返霍比屯"],
];

export const hotelPlans = [
  {
    place: "皇后镇",
    date: "9月29日—10月2日",
    nights: "4晚",
    label: "已预订",
    name: "皇后镇已订房源",
    rating: "订单已确认",
    ratingDetail: "2位客人 · 9月29日—10月3日 · 15:00 后入住",
    reason: "用户已确认四晚订单。为保护隐私，具体地址、房东和入户信息不公开；行车路线以当日导航为准。",
    facts: ["2位客人", "9月24日14:00前可免费取消", "具体信息私下保存"],
    backup: "如主动取消后需要替代，再从现有皇后镇研究候选重新核验即时库存与价格。",
    links: [
      ["原研究候选官网", "https://www.ihg.com/holidayinn/hotels/us/en/queenstown/zqnrm/hoteldetail"],
      ["原研究候选住客评分", "https://www.booking.com/hotel/nz/holiday-inn-queenstown-remarkables-park.html"],
      ["研究备选官网", "https://www.therees.co.nz/"],
    ],
  },
  {
    place: "瓦纳卡",
    date: "10月3—4日",
    nights: "2晚",
    label: "已预订",
    name: "Wanaka Luxury Apartments",
    rating: "Booking.com 订单已确认",
    ratingDetail: "2位成人 · 一卧室公寓 · 两晚NZD 660（确认时待扣款）",
    reason: "已确认的两晚订单保留湖岸步行、厨房和免费停车优势；旧官网直订报价只作为历史比价，不替代订单。",
    facts: ["步行约10分钟到湖边", "免费停车", "9月18日23:59前可全额退款（页面未标时区）"],
    backup: "West Meadows of Wanaka——35 m²特大床一室公寓、评分9.2，但步行湖边不如首选。",
    links: [
      ["住宿官网（直订历史比价）", "https://www.wanakaluxuryapartments.co.nz/"],
      ["住客评分", "https://www.booking.com/hotel/nz/wanaka-luxury-apartments.html"],
      ["备选官网", "https://westmeadowswanaka.co.nz/"],
    ],
  },
  {
    place: "奥拉基 / 库克山",
    date: "10月5日",
    nights: "1晚",
    label: "已预订",
    name: "The Hermitage · Mt Cook Motel Studio Queen",
    rating: "官网已确认",
    ratingDetail: "确认号已私下保存 · 含双人早餐 · 已支付NZD 504",
    reason: "冬宫官网预订已确认；住在库克山村内，避免 Big Sky 后夜间驾驶回 Twizel，并保留次晨直升机天气候补的便利。10月入住需到 Mt Cook Lodge 办理入住。",
    facts: ["确认号已私下保存", "Queen床与完整厨房", "含双人早餐", "免费停车", "入住前48小时以外可取消"],
    backup: "如主动取消后需要替代，可重新核验 Omahau Down、Pukaki / Twizel 民宿的即时库存。",
    links: [
      ["冬宫含早套餐", "https://book.hermitage.co.nz/onecart/wbe/room/20104/hermitage/2026-10-05/2026-10-06/BBSAVE10/2"],
      ["Mt Cook Motels 官网说明", "https://www.hermitage.co.nz/stay/mt-cook-motels/"],
      ["Booking备选", "https://www.booking.com/hotel/nz/omahau-down.html"],
    ],
  },
  {
    place: "基督城",
    date: "10月7日",
    nights: "1晚",
    label: "已预订",
    name: "基督城已订房源",
    rating: "订单已确认",
    ratingDetail: "2位客人 · 10月7日—8日 · 15:00 后入住、10:00 前退房",
    reason: "用户已确认一晚订单。为保护隐私，具体地址、房东和入户信息不公开；10月8日仍按11:00在机场还车安排。",
    facts: ["2位客人", "10月2日15:00前可免费取消", "具体信息私下保存"],
    backup: "如主动取消后需要替代，再从现有基督城研究候选重新核验即时库存与价格。",
    links: [
      ["原研究候选官网", "https://all.accor.com/hotel/6592/index.en.shtml"],
      ["原研究候选住客评分", "https://www.booking.com/hotel/nz/novotel-christchurch-cathedral-square.zh-cn.html"],
      ["研究备选官网", "https://www.distinctionhotelschristchurch.co.nz/"],
    ],
  },
];

export const activityBookingPlans = [
  {
    id: "walter-peak",
    dateKey: "2026-10-02",
    calendarTitle: "Walter Peak 烧烤巡游",
    calendarTitleEn: "Walter Peak cruise & BBQ",
    title: "Walter Peak 湖上巡游 + 高地农场烧烤",
    titleEn: "Walter Peak Gourmet BBQ Dining",
    operator: "RealNZ · TSS Earnslaw",
    date: "10月2日 · 13:00—16:30",
    dateEn: "2 Oct · 13:00–16:30",
    status: "已选场次 · 待付款",
    statusEn: "Slot selected · payment pending",
    statusTone: "selected",
    unitPrice: "NZ$219 / 人",
    unitPriceEn: "NZ$219 / adult",
    total: "NZ$438",
    totalEn: "NZ$438",
    bookingUrl: "https://fareharbor.com/embeds/book/wayfaregroup/items/257722/availability/1923877075/book/?flow=1064984",
    bookingLabel: "继续官网预订",
    bookingLabelEn: "Continue official booking",
    detail: "2位成人；乘 TSS Earnslaw 蒸汽船往返，含 Walter Peak 烧烤午餐。",
    detailEn: "Two adults; return cruise on TSS Earnslaw with the Walter Peak barbecue lunch.",
    policy: "出发前至少24小时（新西兰时间）取消或改期可退款。",
    policyEn: "Change or cancel at least 24 hours before departure, New Zealand time, for a refund.",
  },
  {
    id: "mount-cook-helicopter",
    dateKey: "2026-10-05",
    calendarTitle: "冰川直升机",
    calendarTitleEn: "Glacier helicopter",
    title: "Glacier Highlights 直升机",
    titleEn: "Glacier Highlights helicopter",
    operator: "Mt Cook Ski Planes & Helicopters",
    date: "10月5日 · 15:30前后",
    dateEn: "5 Oct · around 15:30",
    status: "参考档位 · 待付款前复核",
    statusEn: "Reference fare · recheck before payment",
    statusTone: "attention",
    unitPrice: "参考 NZ$649 / 人",
    unitPriceEn: "Reference NZ$649 / adult",
    total: "参考 NZ$1,298",
    totalEn: "Reference NZ$1,298",
    bookingUrl: "https://www.mtcookskiplanes.com/glacier-highlights/",
    bookingLabel: "打开运营方官网",
    bookingLabelEn: "Open operator website",
    detail: "2位成人；约45分钟。当前仅保留参考价，付款前须重新确认精确总价及手续费。",
    detailEn: "Two adults; about 45 minutes. This is a reference fare; confirm the exact total and any fees before payment.",
    policy: "项目受天气影响；付款前确认运营方的改期、天气取消和退款条款。",
    policyEn: "Weather-dependent; confirm rescheduling, weather cancellation and refund terms before payment.",
  },
  {
    id: "mount-cook-stargazing",
    dateKey: "2026-10-05",
    calendarTitle: "Big Sky 观星",
    calendarTitleEn: "Big Sky Stargazing",
    title: "Big Sky Stargazing 观星",
    titleEn: "Big Sky Stargazing",
    operator: "The Hermitage Hotel",
    date: "10月5日 · 较晚场",
    dateEn: "5 Oct · later session",
    status: "场次与语言待复核",
    statusEn: "Session and language to recheck",
    statusTone: "attention",
    unitPrice: "参考 NZ$159 / 人起",
    unitPriceEn: "Reference from NZ$159 / adult",
    total: "参考 NZ$318 起",
    totalEn: "Reference from NZ$318",
    bookingUrl: "https://book.hermitage.co.nz/onecart/activities/activitiesList/20104/hermitage?activityId=129&selectedDate=2026-10-05&partySize=2",
    bookingLabel: "打开官网活动页",
    bookingLabelEn: "Open official activity page",
    detail: "2位成人；约75—90分钟。优先较晚场，并在付款前确认是否提供普通话讲解。",
    detailEn: "Two adults; about 75–90 minutes. Prefer a later session and confirm Mandarin commentary before payment.",
    policy: "云量和天气可能改变活动形式；付款前重新核对当天场次、余位和退款方案。",
    policyEn: "Cloud and weather may change the format; recheck the session, availability and refund arrangement before payment.",
  },
  {
    id: "oamaru-penguins",
    dateKey: "2026-10-06",
    calendarTitle: "小蓝企鹅晚场",
    calendarTitleEn: "Blue-penguin evening",
    title: "奥马鲁小蓝企鹅归巢晚场",
    titleEn: "Ōamaru blue-penguin evening viewing",
    operator: "Ōamaru Blue Penguin Colony",
    date: "10月6日 · 20:00",
    dateEn: "6 Oct · 20:00",
    status: "两档可选 · 待预订",
    statusEn: "Two tiers available · booking pending",
    statusTone: "available",
    unitPrice: "General NZ$50 / 人 · Premium NZ$70 / 人",
    unitPriceEn: "General NZ$50 / adult · Premium NZ$70 / adult",
    total: "2人 NZ$100 或 NZ$140",
    totalEn: "NZ$100 or NZ$140 for two",
    bookingUrl: "https://book.penguins.co.nz/activity/selection?filter=ProdGroup-General&date=2026-10-06",
    bookingLabel: "打开指定日期官网",
    bookingLabelEn: "Open dated official booking",
    detail: "选择 General 或 Premium 其中一档；企鹅票尚未预订，付款前重新确认余位。",
    detailEn: "Choose either General or Premium. The ticket is not booked; recheck availability before payment.",
    policy: "晚场禁止拍照、录像及亮屏；19:30抵达并遵守保护区现场规则。",
    policyEn: "No photography, filming or bright screens during the evening viewing; arrive at 19:30 and follow colony rules.",
  },
  {
    id: "hobbiton",
    dateKey: "2026-10-09",
    calendarTitle: "霍比屯大巴日游",
    calendarTitleEn: "Hobbiton coach tour",
    title: "GreatSights 霍比屯大巴日游",
    titleEn: "GreatSights Hobbiton coach day tour",
    operator: "GreatSights · GS10H",
    date: "10月9日 · 07:00报到",
    dateEn: "9 Oct · check in 07:00",
    status: "已核验可选 · 待预订",
    statusEn: "Selectable when checked · booking pending",
    statusTone: "available",
    unitPrice: "NZ$259 / 人",
    unitPriceEn: "NZ$259 / adult",
    total: "2人标价 NZ$518",
    totalEn: "Listed NZ$518 for two",
    bookingUrl: "https://www.greatsights.co.nz/new-zealand-tour-destinations/hobbiton-tours/hobbiton-movie-set-day-tour/",
    bookingLabel: "打开 GreatSights 官网",
    bookingLabelEn: "Open GreatSights website",
    detail: "07:15从 SkyCity Coach Terminal 出发，约15:30返回；支付页附加费尚未核验。",
    detailEn: "Departs SkyCity Coach Terminal at 07:15 and returns around 15:30; payment-page fees remain unverified.",
    policy: "官网写明出发前2小时可免费取消；付款前再次核对产品代码、集合点和条款。",
    policyEn: "The site states free cancellation up to two hours before departure; reconfirm the product, meeting point and terms before payment.",
  },
];

export const activityBookingSummary = {
  checkedAt: "2026-07-29",
  note: "各项活动分别核价；企鹅有二选一档位，且部分价格仍是参考价，因此不显示误导性的单一合计。",
  noteEn: "Activities are itemised. The penguin viewing has alternative tiers and some fares remain references, so no misleading single total is shown.",
};

export const bookingItems = [
  ["flight-jq295", "JQ295 奥克兰→皇后镇 · 已出票", "9月29日08:15—10:10；经济舱；电子客票于2026年8月3日出具，票面状态OK。当前截图对应单人票面总额CNY 691（票价CNY 671 + 税费CNY 20）；另一位乘客仍需以其电子客票单独确认。"],
  ["south-car", "Budget 南岛租车 · 已预订", "9月29日11:00皇后镇机场取车；10月8日11:00基督城机场还车。Mazda CX-30或同级、自动挡、不限里程，9 × 24小时，NZD 1,685.98已预付；截图未展示的押金、保障与退改细则取车前复核。"],
  ["hotel-auckland-city", "奥克兰市中心住宿 · 已预订", "Hotel Grand Chancellor Auckland 已确认10月8日入住、10月10日退房；入住14:00—00:00，退房00:00—11:00。当前订单页未展示总价、取消或付款状态，不作推断。"],
  ["hotel-queenstown", "皇后镇住宿 · 已预订", "已确认9月29日入住4晚、2位客人；9月24日14:00前可免费取消。具体地址、房东和入户信息私下保存。"],
  ["hotel-wanaka", "瓦纳卡住宿 · 已预订", "Wanaka Luxury Apartments 已确认10月3日入住2晚、2位成人、一卧室公寓；NZD 660，确认时待扣款。"],
  ["mount-cook", "库克山住宿", "已预订：The Hermitage · Mt Cook Motel Studio Queen，10月5日1晚，含双人早餐，确认号已私下保存，已支付 NZD 504。"],
  ["mount-cook-helicopter", "库克山直升机", "10月5日15:30前后；Glacier Highlights 约45分钟，2人参考 NZ$1,298，确认天气取消可退款。"],
  ["mount-cook-stargazing", "Big Sky Stargazing 观星", "10月5日晚较晚场；约75—90分钟，2人 NZ$318 起，可询问中文讲解。"],
  ["hotel-christchurch", "基督城住宿 · 已预订", "已确认10月7日入住、10月8日退房、2位客人；15:00 后入住、10:00 前退房，10月2日15:00前可免费取消。具体地址、房东和入户信息私下保存。"],
  ["hotel-oamaru", "奥马鲁住宿 · 已调研待预订", "10月6日住奥马鲁1晚；已完成精品套房、公寓民宿、自助客栈与传统酒店的精确日期官网比选，Mariner Suites 为首选，仍待付款预订；付款前重新核验最新库存、退改规则及晚到取钥匙安排。"],
  ["oamaru-penguins", "奥马鲁小蓝企鹅晚场 · 待预订", "10月6日20:00官方小蓝企鹅归巢晚场；General 2人NZD 100、Premium 2人NZD 140为2026-07-29核验价格，付款前重新确认余位与退改规则。"],
  ["walter-peak", "Walter Peak 湖上巡游 + 高地农场烧烤", "10月2日；优先选择中午或下午较早场，全程约3.5—4小时。"],
  ["flight-jq236", "JQ236 基督城→奥克兰 · 已出票", "10月8日13:50—15:10；经济舱；电子客票于2026年8月3日出具，票面状态OK。当前截图对应单人票面总额CNY 794（票价CNY 746 + 税费CNY 48）；另一位乘客仍需以其电子客票单独确认。"],
  ["north-car-cancel", "北岛租车订单 · 待用户取消", "已存在真实 Budget 订单；现行程不再取车，但修改本页面不等于取消订单。请在 Budget 官网管理订单中主动取消并保存确认。"],
  ["hobbiton", "GreatSights 霍比屯大巴日游 · 待预订", "10月9日 GS10H 已核验可选：07:00 SkyCity Coach Terminal 报到，07:15出发，约15:30返回；NZD 259/成人，2人标价NZD 518，支付页附加费未知；提前2小时免费取消。"],
];

export const notes = [
  {
    title: "道路与天气",
    items: [
      "每天早晨查看 NZTA 实时路况。",
      "Crown Range 若积雪或封路，改走 Cromwell 路线。",
      "直升机与户外观星都看天气：10月5日白天确认飞行，傍晚再确认观星；取消时以改期或退款为先。",
      "南岛避免夜间驾驶；雪链随车携带。",
    ],
  },
  {
    title: "航班与行李",
    items: [
      "Jetstar 基础票通常只含合计 7kg 手提行李。",
      "两段 Jetstar 国内航班的电子客票截图均显示状态 OK，出票日期为2026年8月3日；当前截图仅能确认其中一位乘客。",
      "另一位乘客仍需逐段核对电子客票；同时确认乘机人姓名、随身与托运行李规则，并按需要另购托运行李。",
      "10月10日购物品提前分配到托运行李。",
    ],
  },
  {
    title: "租车关键点",
    items: [
      "南岛 Budget 订单已确认：9月29日11:00皇后镇机场取车，10月8日11:00基督城机场还车；预订号已私下保存。",
      "Mazda CX-30或同级、自动挡、不限里程；9 × 24小时异地还车，订单总额 NZD 1,685.98 已预付。",
      "订单截图未显示取消、押金、预授权与保障细则，取车前仍需按 Budget 条款复核。",
      "北岛 Budget 订单现为待取消：网站改成大巴行程不会同步取消真实订单，需在 Budget 官网管理订单中主动操作并保存取消确认。",
      "不走 Skippers Road；车顶、底盘、涉水及其他条款除外损失仍可能需要全额自付。",
    ],
  },
];
