import { assetPath } from "./assets";

export const tabs = [
  { value: "overview", label: "行程总览", short: "总览" },
  { value: "south", label: "南岛行程", short: "南岛" },
  { value: "north", label: "北岛与购物", short: "北岛" },
  { value: "booking", label: "预订清单", short: "预订" },
  { value: "notes", label: "注意事项", short: "提醒" },
];

export const stats = [
  { label: "南岛租车", value: "8天", note: "皇后镇取 · 基督城还" },
  { label: "最长连住", value: "4晚", note: "皇后镇慢慢玩" },
  { label: "奥克兰购物", value: "1整天", note: "CBD + Newmarket" },
  { label: "长途驾驶", value: "2天", note: "其余均为舒缓节奏" },
];

export const mapStops = [
  { tag: "SZX", name: "深圳", date: "9/28", desc: "出发城市，国际航班起点", color: "#6f8fb5", position: [22.5431, 114.0579] },
  { tag: "KUL", name: "吉隆坡转机", date: "9/28", desc: "马来西亚转机节点", color: "#7b8f6a", position: [2.7456, 101.7072] },
  { tag: "AKL", name: "奥克兰", date: "9/28 · 10/8 · 10/10", desc: "机场酒店、购物日、返程", color: "#f2b86b", position: [-36.8509, 174.7645] },
  { tag: "ZQN", name: "皇后镇", date: "9/29—10/3", desc: "连住4晚，湖边慢慢适应", color: "#df7659", position: [-45.0312, 168.6626] },
  { tag: "MFN", name: "米尔福德峡湾", date: "10/2", desc: "唯一早起，巴士 + 游船", color: "#347e90", position: [-44.6414, 167.8974] },
  { tag: "WKA", name: "瓦纳卡", date: "10/3—10/5", desc: "连住2晚，湖边与轻步道", color: "#8ab59b", position: [-44.698, 169.136] },
  { tag: "AOR", name: "库克山", date: "10/5", desc: "普卡基湖、轻量步道", color: "#7895b2", position: [-43.735, 170.0967] },
  { tag: "CHC", name: "基督城", date: "10/6—10/7", desc: "还车、飞回奥克兰", color: "#9d7f66", position: [-43.5321, 172.6362] },
  { tag: "HBT", name: "霍比屯", date: "10/9", desc: "建议中午场", color: "#9dbb54", position: [-37.8576, 175.6792] },
  { tag: "ROT", name: "罗托鲁瓦", date: "10/9—10/10", desc: "Te Puia 地热与毛利文化", color: "#b46e55", position: [-38.1368, 176.2497] },
];

export const gallery = [
  { src: assetPath("images/queenstown.webp"), alt: "皇后镇与瓦卡蒂普湖", kicker: "SOUTH ISLAND", title: "皇后镇 · 湖与山之间" },
  { src: assetPath("images/milford.webp"), alt: "米尔福德峡湾群山与水面", kicker: "FIORDLAND", title: "米尔福德峡湾" },
  { src: assetPath("images/aoraki.webp"), alt: "普卡基湖远望奥拉基库克山", kicker: "MACKENZIE", title: "库克山与普卡基湖" },
  { src: assetPath("images/auckland.webp"), alt: "奥克兰市中心天际线", kicker: "NORTH ISLAND", title: "奥克兰 · 城市购物日" },
];

export const southDays = [
  {
    date: "9月28日",
    weekday: "周一",
    title: "深圳 → 吉隆坡 → 奥克兰",
    subtitle: "马来西亚转机，落地后直接休息",
    stay: "奥克兰机场；当天不进市区。",
    intensity: "低",
    color: "#347e90",
    events: [
      ["出发前", "深圳机场值机、托运行李"],
      ["夜间", "深圳起飞，前往马来西亚"],
      ["转机", "吉隆坡机场转机"],
      ["续飞", "吉隆坡 → 奥克兰"],
      ["23:50", "抵达奥克兰"],
      ["约01:00", "完成入境、取行李"],
      ["01:15", "入住机场酒店"],
    ],
  },
  {
    date: "9月29日",
    weekday: "周二",
    title: "奥克兰 → 皇后镇",
    subtitle: "NZ619 与南岛取车",
    stay: "皇后镇第1晚；只开机场到酒店。",
    intensity: "中",
    color: "#df7659",
    events: [
      ["09:45", "前往国内航站楼"],
      ["11:35", "NZ619 起飞"],
      ["13:30", "抵达、机场午餐"],
      ["15:30", "Omega 取车"],
      ["16:15", "入住、湖边散步"],
    ],
  },
  {
    date: "9月30日",
    weekday: "周三",
    title: "皇后镇市区",
    subtitle: "花园、湖边与 Skyline",
    stay: "基本不开车，作为适应日。",
    intensity: "低",
    color: "#8ab59b",
    events: [
      ["10:30", "皇后镇花园、湖边"],
      ["12:30", "市区午餐"],
      ["14:00", "Skyline 缆车"],
      ["16:30", "咖啡、逛街"],
      ["18:30", "晚餐"],
    ],
  },
  {
    date: "10月1日",
    weekday: "周四",
    title: "皇后镇 ⇄ 格林诺奇",
    subtitle: "湖岸公路半日游",
    stay: "约92km / 2小时；不去 Skippers Road。",
    intensity: "中",
    color: "#7895b2",
    events: [
      ["10:00", "皇后镇出发"],
      ["10:30", "Bob’s Cove"],
      ["11:15", "Bennett’s Bluff"],
      ["12:00", "格林诺奇午餐"],
      ["13:30", "Lagoon 木栈道"],
      ["16:30", "回到皇后镇"],
    ],
  },
  {
    date: "10月2日",
    weekday: "周五",
    title: "米尔福德峡湾",
    subtitle: "巴士 + 峡湾游船",
    stay: "全程最累约12—13小时，但不需要自己开车。",
    intensity: "高",
    color: "#123f36",
    events: [
      ["05:50", "起床"],
      ["06:45", "巴士出发"],
      ["上午", "蒂阿瑙及沿途观景"],
      ["下午", "峡湾游船"],
      ["约20:00", "返回皇后镇"],
    ],
  },
  {
    date: "10月3日",
    weekday: "周六",
    title: "皇后镇 → 箭镇 → 瓦纳卡",
    subtitle: "Crown Range 与 Cardrona",
    stay: "约80km / 2小时；坏天气改走 Cromwell。",
    intensity: "中",
    color: "#df7659",
    events: [
      ["10:00", "退房出发"],
      ["10:30", "箭镇、午餐"],
      ["13:00", "前往瓦纳卡"],
      ["13:45", "Crown Range 观景"],
      ["14:30", "Cardrona 咖啡"],
      ["16:00", "抵达瓦纳卡"],
    ],
  },
  {
    date: "10月4日",
    weekday: "周日",
    title: "瓦纳卡",
    subtitle: "整日不换酒店",
    stay: "根据天气临时决定下午项目。",
    intensity: "低",
    color: "#8ab59b",
    events: [
      ["10:30", "湖边、That Wanaka Tree"],
      ["12:30", "午餐"],
      ["14:00", "Puzzling World 或 Mount Iron"],
      ["16:30", "咖啡、看日落"],
      ["18:30", "晚餐"],
    ],
  },
  {
    date: "10月5日",
    weekday: "周一",
    title: "瓦纳卡 → 库克山",
    subtitle: "Lindis Pass 与普卡基湖",
    stay: "约205km / 3—3.5小时；不走胡克谷全程。",
    intensity: "中",
    color: "#7895b2",
    events: [
      ["08:45", "退房出发"],
      ["10:15", "Lindis Pass"],
      ["11:15", "Omarama 午餐、加油"],
      ["13:30", "Lake Pukaki"],
      ["14:30", "库克山村"],
      ["15:30", "轻量步道"],
    ],
  },
  {
    date: "10月6日",
    weekday: "周二",
    title: "库克山 → 蒂卡波 → 基督城",
    subtitle: "南岛最长自驾日",
    stay: "约330km / 4—4.5小时；中途休息一次。",
    intensity: "高",
    color: "#123f36",
    events: [
      ["09:30", "离开库克山"],
      ["11:00", "蒂卡波教堂、湖边、午餐"],
      ["13:30", "前往基督城"],
      ["17:00", "抵达、入住"],
    ],
  },
  {
    date: "10月7日",
    weekday: "周三",
    title: "基督城 → 奥克兰",
    subtitle: "还车与 JQ242",
    stay: "奥克兰机场第1晚；第二天不用搬酒店。",
    intensity: "中",
    color: "#df7659",
    events: [
      ["10:00", "市区、Riverside Market"],
      ["12:00", "午餐"],
      ["13:00", "植物园或咖啡"],
      ["15:30", "Omega 还车"],
      ["20:30", "JQ242 起飞"],
      ["21:50", "抵达奥克兰"],
    ],
  },
];

export const northDays = [
  {
    date: "10月8日",
    weekday: "周四",
    title: "奥克兰购物日",
    subtitle: "CBD + Newmarket",
    stay: "奥克兰机场第2晚；不租车、不搬行李。",
    intensity: "低",
    color: "#f2b86b",
    events: [
      ["09:00", "机场巴士进城"],
      ["10:00", "Queen Street、Britomart"],
      ["12:30", "Commercial Bay 午餐"],
      ["14:00", "Westfield Newmarket"],
      ["18:00", "晚餐"],
      ["19:30", "返回机场酒店"],
    ],
  },
  {
    date: "10月9日",
    weekday: "周五",
    title: "奥克兰 → 霍比屯 → 罗托鲁瓦",
    subtitle: "北岛取车与中午场",
    stay: "约250km / 3.5小时；住宿罗托鲁瓦1晚。",
    intensity: "中",
    color: "#9dbb54",
    events: [
      ["08:30", "奥克兰机场取车"],
      ["09:00", "出发"],
      ["11:20", "抵达 The Shire’s Rest"],
      ["12:00", "霍比屯游览"],
      ["14:30", "午餐"],
      ["16:30", "抵达罗托鲁瓦"],
      ["17:30", "可选 Redwoods 轻松散步"],
    ],
  },
  {
    date: "10月10日",
    weekday: "周六",
    title: "罗托鲁瓦 → 奥克兰机场",
    subtitle: "Te Puia 与返程",
    stay: "约230km / 3小时；航班在次日凌晨。",
    intensity: "中",
    color: "#b46e55",
    events: [
      ["09:00", "Te Puia 地热与毛利文化"],
      ["12:00", "午餐"],
      ["13:30", "直接前往奥克兰机场"],
      ["17:00", "加油、还车"],
      ["18:00", "机场晚餐"],
      ["21:45", "办理国际值机"],
    ],
  },
  {
    date: "10月11日",
    weekday: "周日",
    title: "奥克兰 → 深圳",
    subtitle: "国际航班返程",
    stay: "购物品提前整理托运，不要把液体留在手提行李。",
    intensity: "低",
    color: "#347e90",
    events: [
      ["00:30", "前往登机口"],
      ["01:25", "奥克兰起飞"],
      ["次日01:15", "预计抵达深圳，以最终机票为准"],
    ],
  },
];

export const shoppingStops = [
  ["09:00", "机场 → 市中心", "搭机场巴士前往 SkyCity 附近"],
  ["10:00", "Queen Street", "市中心主购物街，顺路走到 Britomart"],
  ["12:30", "Commercial Bay", "午餐 + 品牌店，不用来回赶"],
  ["14:00", "Westfield Newmarket", "百货、美妆、服装集中采购"],
  ["18:00", "晚餐", "Newmarket 或市中心用餐"],
  ["19:30", "返回机场酒店", "整理购物品，第二天再取车"],
];

export const bookingItems = [
  ["flight-nz619", "NZ619 奥克兰→皇后镇", "9月29日 11:35—13:30；确认托运行李。"],
  ["south-car", "Omega 南岛租车", "9月29日 15:30 取、10月7日 15:30 还；零自付额 + 雪链。"],
  ["mount-cook", "库克山村住宿", "10月5日一晚；全程最需要提前锁定。"],
  ["milford", "米尔福德峡湾", "10月2日 06:45 左右；选酒店附近接车点。"],
  ["flight-jq242", "JQ242 基督城→奥克兰", "10月7日 20:30—21:50；提前添加托运行李。"],
  ["north-car", "北岛租车", "10月9日 08:30 取、10月10日 17:00 还；奥克兰机场取还。"],
  ["hobbiton", "霍比屯", "建议 10月9日 12:00 场，至少提前20分钟抵达。"],
  ["hotels", "连住型住宿", "皇后镇4晚、瓦纳卡2晚、奥克兰机场2晚。"],
];

export const notes = [
  {
    title: "道路与天气",
    items: [
      "每天早晨查看 NZTA 实时路况。",
      "Crown Range 若积雪或封路，改走 Cromwell 路线。",
      "南岛避免夜间驾驶；雪链随车携带。",
    ],
  },
  {
    title: "航班与行李",
    items: [
      "Jetstar 基础票通常只含合计 7kg 手提行李。",
      "两段国内航班都要在付款前确认托运行李。",
      "10月10日购物品提前分配到托运行李。",
    ],
  },
  {
    title: "租车关键点",
    items: [
      "南岛取还车时间都填 15:30，控制在 8 个 24 小时内。",
      "10月7日营业时间内还车，避开非营业时间费用。",
      "不走 Skippers Road；碎石路先看租车条款。",
    ],
  },
];
